[package]
org = "wso2healthcare"
name = "AUBasePatientAPI"
version = "1.0.2"
distribution = "2201.7.0"
authors = ["WSO2 Healthcare"]
keywords = ["Healthcare", "FHIR", "Patient", "r4", "aubase"]

[build-options]
observabilityIncluded = true

[[dependency]]
org="ballerinax"
name="health.fhir.r4"
version="4.1.0"
