[package]
org = "wso2"
name = "Hl7v2ToFhirR4Service"
version = "1.2.0"
distribution = "2201.12.10"
authors = ["Ballerina"]
keywords = ["Area/Healthcare", "Industry/Healthcare", "Type/Template", "HL7V2 to FHIR", "FHIR", "HL7V2"]
template = true

[build-options]
observabilityIncluded = true
optimizeDependencyCompilation = true