package compartment

// EncounterCompartment is the FHIR R4 Encounter compartment definition.
// Source: https://hl7.org/fhir/R4/compartmentdefinition-encounter.html
var EncounterCompartment = &Definition{
	CompartmentType: "Encounter",
	Inclusions: map[string][]string{
		"Composition":           {"encounter"},
		"DiagnosticReport":      {"encounter"},
		"DocumentReference":     {"encounter"},
		"Encounter":             {"", ""}, // self
		"Flag":                  {"encounter"},
		"List":                  {"encounter"},
		"MedicationRequest":     {"encounter"},
		"NutritionOrder":        {"encounter"},
		"Observation":           {"encounter"},
		"Procedure":             {"encounter"},
		"RiskAssessment":        {"encounter"},
		"ServiceRequest":        {"encounter"},
		"VisionPrescription":    {"encounter"},
	},
}

// PractitionerCompartment is the FHIR R4 Practitioner compartment definition.
// Source: https://hl7.org/fhir/R4/compartmentdefinition-practitioner.html
var PractitionerCompartment = &Definition{
	CompartmentType: "Practitioner",
	Inclusions: map[string][]string{
		"Account":                  {"subject"},
		"AdverseEvent":             {"recorder"},
		"AllergyIntolerance":       {"recorder", "asserter"},
		"Appointment":              {"actor"},
		"AppointmentResponse":      {"actor"},
		"AuditEvent":               {"agent"},
		"Basic":                    {"author"},
		"CarePlan":                 {"performer"},
		"CareTeam":                 {"participant"},
		"ChargeItem":               {"enterer", "performer-actor"},
		"Claim":                    {"enterer", "provider", "payee", "care-team"},
		"ClaimResponse":            {"requestor"},
		"ClinicalImpression":       {"assessor"},
		"Communication":            {"sender", "recipient"},
		"CommunicationRequest":     {"sender", "recipient", "requester"},
		"Composition":              {"author", "attester"},
		"Condition":                {"asserter"},
		"Coverage":                 {"policy-holder", "payor"},
		"CoverageEligibilityRequest": {"enterer", "provider"},
		"CoverageEligibilityResponse": {"requestor"},
		"DetectedIssue":            {"author"},
		"DeviceRequest":            {"requester", "performer"},
		"DiagnosticReport":         {"results-interpreter", "performer"},
		"DocumentManifest":         {"author", "recipient"},
		"DocumentReference":        {"author"},
		"Encounter":                {"participant"},
		"EnrollmentRequest":        {"provider"},
		"EpisodeOfCare":            {"care-manager"},
		"ExplanationOfBenefit":     {"enterer", "provider", "payee", "care-team"},
		"Flag":                     {"author"},
		"ImagingStudy":             {"interpreter", "performer"},
		"Immunization":             {"performer"},
		"ImmunizationRecommendation": {"information"},
		"Invoice":                  {"participant", "recipient"},
		"List":                     {"source"},
		"MeasureReport":            {"reporter"},
		"Media":                    {"operator"},
		"MedicationAdministration": {"performer"},
		"MedicationDispense":       {"performer", "receiver"},
		"MedicationRequest":        {"requester"},
		"MedicationStatement":      {"source"},
		"Observation":              {"performer"},
		"Patient":                  {"general-practitioner"},
		"Procedure":                {"performer"},
		"Provenance":               {"agent"},
		"QuestionnaireResponse":    {"author"},
		"RelatedPerson":            {},
		"RequestGroup":             {"author", "participant"},
		"RiskAssessment":           {"performer"},
		"Schedule":                 {"actor"},
		"ServiceRequest":           {"requester", "performer"},
		"Specimen":                 {"collector"},
		"SupplyRequest":            {"requester"},
		"Task":                     {"owner", "requester"},
		"VisionPrescription":       {"prescriber"},
	},
}
