[package]
org = "wso2"
name = "MemberMatchService"
version = "0.1.0"
distribution = "2201.10.2"

[build-options]
observabilityIncluded = true

[[dependency]]
org="ballerinax"
name="health.fhir.r4.davincihrex100"
version="1.0.0"

[[dependency]]
org="ballerinax"
name="health.fhirr4"
version="1.3.3"
