[package]
org = "ballerinax"
name = "ballerina_iam_service_extensions"
version = "0.1.0"
distribution = "2201.12.10"
keywords = ["Healthcare", "IAM", "extensions"]

[build-options]
observabilityIncluded = true
