// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).

// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at

// http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
// AUTO-GENERATED FILE.
// This file is auto-generated by Ballerina.

import ballerinax/health.fhir.r4;

// This API config is used for batch validation requests
final r4:ResourceAPIConfig apiConfig = {
    resourceType: "Bundle",
    profiles: [

    ],
    defaultProfile: (),
    searchParameters: [],
    // TEMPORARY (api-conformance): $find-code, $closure and $versions are
    // system-level (base) operations with no owning FHIR resource type, so they
    // are registered here rather than under ValueSet/CodeSystem/ConceptMap. They
    // were previously implemented as their own raw http:InterceptableServices on
    // baseListener with a literal `$`-escaped path segment (e.g. /fhir/r4/\$find\-code),
    // which relies on ballerina/http's compiled path dispatcher recognizing that
    // literal segment. That dispatcher regressed in http 2.14.13 (bundled with
    // Ballerina distribution 2201.12.10): a raw `$` in the request path 404s and
    // only a percent-encoded `%24` matches. Declaring them as resource functions
    // here instead routes them through fhirr4:Listener's own reflection-based
    // dispatch (string-matching req.rawPath at runtime, see
    // ballerinax/health.fhirr4's http_service_builder.bal), which never goes
    // through the broken compiled matcher and accepts a raw `$` correctly.
    operations: [
        {
            name: "find-code",
            active: true,
            preProcessor: findCodeAndClosurePreProcessor,
            // registerResourceOperation (ballerinax/health.fhirr4) only registers an
            // operation when `parameters` is present as an array - even an empty one.
            // Omitting it silently drops the operation ("Unknown operation").
            parameters: [],
            additionalProperties: {
                meta: {
                    operationLevels: [
                        {
                            "instanceLevel": false,
                            "typeLevel": false,
                            "systemLevel": true
                        }
                    ]
                }
            }
        },
        {
            name: "closure",
            active: true,
            preProcessor: findCodeAndClosurePreProcessor,
            parameters: [],
            additionalProperties: {
                meta: {
                    operationLevels: [
                        {
                            "instanceLevel": false,
                            "typeLevel": false,
                            "systemLevel": true
                        }
                    ]
                }
            }
        },
        {
            name: "versions",
            active: true,
            parameters: [],
            additionalProperties: {
                meta: {
                    operationLevels: [
                        {
                            "instanceLevel": false,
                            "typeLevel": false,
                            "systemLevel": true
                        }
                    ]
                }
            }
        }
    ],
    serverConfig: (),
    authzConfig: ()
};

# ######################################################################################################################
# ValueSet API Configs                                                                                                  #
# ######################################################################################################################

final r4:ResourceAPIConfig valueSetApiConfig = {
    resourceType: "ValueSet",
    profiles: [
        "http://hl7.org/fhir/StructureDefinition/ValueSet"
    ],
    defaultProfile: (),
    searchParameters: [
        {
            name: "_id",
            active: true,
            information: {
                description: "The ID of the resource",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/Resource-id"
            }
        },
        {
            name: "coding",
            active: true
        },
        {
            name: "url",
            active: true,
            information: {
                description: "The uri that identifies the value set",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/conformance-url"
            }
        },
        {
            name: "version",
            active: true,
            information: {
                description: "The business version of the value set",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/conformance-version"
            }
        },
        {
            name: "name",
            active: true,
            information: {
                description: "Computationally friendly name of the value set",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/conformance-name"
            }
        },
        {
            name: "title",
            active: true,
            information: {
                description: "The human-friendly name of the value set",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/conformance-title"
            }
        },
        {
            name: "status",
            active: true,
            information: {
                description: "The current status of the value set",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/conformance-status"
            }
        },
        {
            name: "date",
            active: true,
            information: {
                description: "The value set publication date",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/conformance-date"
            }
        },
        {
            name: "publisher",
            active: true,
            information: {
                description: "Name of the publisher of the value set",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/conformance-publisher"
            }
        },
        {
            name: "description",
            active: true,
            information: {
                description: "The description of the value set",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/conformance-description"
            }
        },
        {
            name: "identifier",
            active: true,
            information: {
                description: "External identifier for the value set",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/conformance-identifier"
            }
        },
        {
            name: "jurisdiction",
            active: true,
            information: {
                description: "Intended jurisdiction for the value set",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/conformance-jurisdiction"
            }
        },
        {
            name: "context",
            active: true,
            information: {
                description: "A use context assigned to the value set",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/conformance-context"
            }
        },
        {
            name: "context-type",
            active: true,
            information: {
                description: "A type of use context assigned to the value set",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/conformance-context-type"
            }
        },
        {
            name: "context-quantity",
            active: true,
            information: {
                description: "A quantity- or range-valued use context assigned to the value set",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/conformance-context-quantity"
            }
        },
        {
            name: "expansion",
            active: true,
            information: {
                description: "Identifies the value set expansion (business identifier)",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/ValueSet-expansion"
            }
        },
        {
            name: "reference",
            active: true,
            information: {
                description: "A code system included or excluded in the value set or an imported value set",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/ValueSet-reference"
            }
        }
    ]
    ,
    operations: [
        {
            name: "expand",
            active: true,
            // TEMPORARY (api-conformance): tolerate unknown operation params (e.g. the
            // test runner's "uuid"). See conformance_shim.bal.
            preProcessor: lenientOperationPreProcessor,
            additionalProperties: {
                meta: {
                    operationLevels: [
                        {
                            "instanceLevel": true,
                            "typeLevel": true,
                            "systemLevel": false,
                            "resource": [
                                "ValueSet"
                            ]
                        }
                    ]
                }
            },
            parameters: [
                {
                    name: "url",
                    active: true,
                    min: 0
                },
                {
                    name: "tx-resource",
                    active: true,
                    min: 0
                },
                {
                    name: "uuid",
                    active: true,
                    min: 0
                },
                {
                    name: "valueSet",
                    active: true,
                    min: 0
                },
                {
                    name: "valueSetVersion",
                    active: true,
                    min: 0
                },
                {
                    name: "context",
                    active: true,
                    min: 0
                },
                {
                    name: "contextDirection",
                    active: true,
                    min: 0
                },
                {
                    name: "filter",
                    active: true,
                    min: 0
                },
                {
                    name: "date",
                    active: true,
                    min: 0
                },
                {
                    name: "offset",
                    active: true,
                    min: 0
                },
                {
                    name: "count",
                    active: true,
                    min: 0
                },
                {
                    name: "includeDesignations",
                    active: true,
                    min: 0
                },
                {
                    name: "designation",
                    active: true,
                    min: 0
                },
                {
                    name: "includeDefinition",
                    active: true,
                    min: 0
                },
                {
                    name: "activeOnly",
                    active: true,
                    min: 0
                },
                {
                    name: "excludeNested",
                    active: true,
                    min: 0
                },
                {
                    name: "excludeNotForUI",
                    active: true,
                    min: 0
                },
                {
                    name: "excludePostCoordinated",
                    active: true,
                    min: 0
                },
                {
                    name: "displayLanguage",
                    active: true,
                    min: 0
                },
                {
                    name: "exclude-system",
                    active: true,
                    min: 0
                },
                {
                    name: "system-version",
                    active: true,
                    min: 0
                },
                {
                    name: "check-system-version",
                    active: true,
                    min: 0
                },
                {
                    name: "force-system-version",
                    active: true,
                    min: 0
                }
            ]
        },
        {
            name: "validate-code",
            active: true,
            // TEMPORARY (api-conformance): tolerate unknown operation params (e.g. the
            // test runner's "uuid"). See conformance_shim.bal.
            preProcessor: lenientOperationPreProcessor,
            additionalProperties: {
                meta: {
                    operationLevels: [
                        {
                            "instanceLevel": true,
                            "typeLevel": true,
                            "systemLevel": false,
                            "resource": [
                                "ValueSet"
                            ]
                        }
                    ]
                }
            },
            parameters: [
                {
                    name: "url",
                    active: true,
                    min: 0
                },
                {
                    name: "context",
                    active: true,
                    min: 0
                },
                {
                    name: "valueSet",
                    active: true,
                    min: 0
                },
                {
                    name: "valueSetVersion",
                    active: true,
                    min: 0
                },
                {
                    name: "code",
                    active: true,
                    min: 0
                },
                {
                    name: "system",
                    active: true,
                    min: 0
                },
                {
                    name: "systemVersion",
                    active: true,
                    min: 0
                },
                {
                    name: "display",
                    active: true,
                    min: 0
                },
                {
                    name: "coding",
                    active: true,
                    min: 0
                },
                {
                    name: "codeableConcept",
                    active: true,
                    min: 0
                },
                {
                    name: "date",
                    active: true,
                    min: 0
                },
                {
                    name: "abstract",
                    active: true,
                    min: 0
                },
                {
                    name: "displayLanguage",
                    active: true,
                    min: 0
                }
            ]
        }
    ],
    serverConfig: (),
    authzConfig: ()
};

# ######################################################################################################################
# CodeSystem API Configs                                                                                                #
# ######################################################################################################################

final r4:ResourceAPIConfig codeSystemApiConfig = {
    resourceType: "CodeSystem",
    profiles: [
        "http://hl7.org/fhir/StructureDefinition/CodeSystem"
    ],
    defaultProfile: (),
    searchParameters: [
        {
            name: "_id",
            active: true,
            information: {
                description: "The ID of the resource",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/Resource-id"
            }
        },
        {
            name: "url",
            active: true,
            information: {
                description: "The uri that identifies the code system",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/conformance-url"
            }
        },
        {
            name: "version",
            active: true,
            information: {
                description: "The business version of the code system",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/conformance-version"
            }
        },
        {
            name: "name",
            active: true,
            information: {
                description: "Computationally friendly name of the code system",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/conformance-name"
            }
        },
        {
            name: "title",
            active: true,
            information: {
                description: "The human-friendly name of the code system",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/conformance-title"
            }
        },
        {
            name: "status",
            active: true,
            information: {
                description: "The current status of the code system",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/conformance-status"
            }
        },
        {
            name: "date",
            active: true,
            information: {
                description: "The code system publication date",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/conformance-date"
            }
        },
        {
            name: "publisher",
            active: true,
            information: {
                description: "Name of the publisher of the code system",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/conformance-publisher"
            }
        },
        {
            name: "description",
            active: true,
            information: {
                description: "The description of the code system",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/conformance-description"
            }
        },
        {
            name: "identifier",
            active: true,
            information: {
                description: "External identifier for the code system",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/conformance-identifier"
            }
        },
        {
            name: "jurisdiction",
            active: true,
            information: {
                description: "Intended jurisdiction for the code system",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/conformance-jurisdiction"
            }
        },
        {
            name: "context",
            active: true,
            information: {
                description: "A use context assigned to the code system",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/conformance-context"
            }
        },
        {
            name: "context-type",
            active: true,
            information: {
                description: "A type of use context assigned to the code system",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/conformance-context-type"
            }
        },
        {
            name: "context-quantity",
            active: true,
            information: {
                description: "A quantity- or range-valued use context assigned to the code system",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/conformance-context-quantity"
            }
        },
        {
            name: "system",
            active: true,
            information: {
                description: "The system for any codes defined by this code system",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/CodeSystem-system"
            }
        },
        {
            name: "content-mode",
            active: true,
            information: {
                description: "not-present | example | fragment | complete | supplement",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/CodeSystem-content-mode"
            }
        },
        {
            name: "language",
            active: true,
            information: {
                description: "A language in which a designation is provided",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/CodeSystem-language"
            }
        },
        {
            name: "supplements",
            active: true,
            information: {
                description: "Find code system supplements for the referenced code system",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/CodeSystem-supplements"
            }
        }
    ],
    operations: [
        {
            name: "lookup",
            active: true,
            // TEMPORARY (api-conformance): tolerate unknown operation params (e.g. the
            // test runner's "uuid"). See conformance_shim.bal.
            preProcessor: lenientOperationPreProcessor,
            additionalProperties: {
                meta: {
                    operationLevels: [
                        {
                            "instanceLevel": false,
                            "typeLevel": true,
                            "systemLevel": false,
                            "resource": [
                                "CodeSystem"
                            ]
                        }
                    ]
                }
            },
            parameters: [
                {
                    name: "code",
                    active: true,
                    min: 0
                },
                {
                    name: "system",
                    active: true,
                    min: 0
                },
                {
                    name: "version",
                    active: true,
                    min: 0
                },
                {
                    name: "coding",
                    active: true,
                    min: 0
                },
                {
                    name: "date",
                    active: true,
                    min: 0
                },
                {
                    name: "displayLanguage",
                    active: true,
                    min: 0
                },
                {
                    name: "property",
                    active: true,
                    min: 0
                }
            ]
        },
        {
            name: "validate-code",
            active: true,
            // TEMPORARY (api-conformance): tolerate unknown operation params (e.g. the
            // test runner's "uuid"). See conformance_shim.bal.
            preProcessor: lenientOperationPreProcessor,
            additionalProperties: {
                meta: {
                    operationLevels: [
                        {
                            "instanceLevel": true,
                            "typeLevel": true,
                            "systemLevel": false,
                            "resource": [
                                "CodeSystem"
                            ]
                        }
                    ]
                }
            },
            parameters: [
                {
                    name: "url",
                    active: true,
                    min: 0
                },
                {
                    name: "codeSystem",
                    active: true,
                    min: 0
                },
                {
                    name: "code",
                    active: true,
                    min: 0
                },
                {
                    name: "version",
                    active: true,
                    min: 0
                },
                {
                    name: "display",
                    active: true,
                    min: 0
                },
                {
                    name: "coding",
                    active: true,
                    min: 0
                },
                {
                    name: "codeableConcept",
                    active: true,
                    min: 0
                },
                {
                    name: "date",
                    active: true,
                    min: 0
                },
                {
                    name: "abstract",
                    active: true,
                    min: 0
                },
                {
                    name: "displayLanguage",
                    active: true,
                    min: 0
                }
            ]
        },
        {
            name: "subsumes",
            active: true,
            // TEMPORARY (api-conformance): tolerate unknown operation params (e.g. the
            // test runner's "uuid"). See conformance_shim.bal.
            preProcessor: lenientOperationPreProcessor,
            additionalProperties: {
                meta: {
                    operationLevels: [
                        {
                            "instanceLevel": true,
                            "typeLevel": true,
                            "systemLevel": false,
                            "resource": [
                                "CodeSystem"
                            ]
                        }
                    ]
                }
            },
            parameters: [
                {
                    name: "codeA",
                    active: true,
                    min: 0
                },
                {
                    name: "codeB",
                    active: true,
                    min: 0
                },
                {
                    name: "system",
                    active: true,
                    min: 0
                },
                {
                    name: "version",
                    active: true,
                    min: 0
                },
                {
                    name: "codingA",
                    active: true,
                    min: 0
                },
                {
                    name: "codingB",
                    active: true,
                    min: 0
                }
            ]
        },
        {
            name: "find-matches",
            active: true,
            parameters: [
                {
                    name: "system",
                    active: true,
                    min: 0
                },
                {
                    name: "version",
                    active: true,
                    min: 0
                },
                {
                    name: "property",
                    active: true,
                    min: 0
                },
                {
                    name: "exact",
                    active: true,
                    min: 1
                },
                {
                    name: "compositional",
                    active: true,
                    min: 0
                }
            ]
        }
    ],
    serverConfig: (),
    authzConfig: ()
};

# ######################################################################################################################
# ConceptMap API Configs                                                                                                #
# ######################################################################################################################

final r4:ResourceAPIConfig conceptMapApiConfig = {
    resourceType: "ConceptMap",
    profiles: [
        "http://hl7.org/fhir/StructureDefinition/ConceptMap"
    ],
    defaultProfile: (),
    searchParameters: [
        {
            name: "_id",
            active: true,
            information: {
                description: "The ID of the resource",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/Resource-id"
            }
        },
        {
            name: "url",
            active: true,
            information: {
                description: "The uri that identifies the concept map",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/conformance-url"
            }
        },
        {
            name: "version",
            active: true,
            information: {
                description: "The business version of the concept map",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/conformance-version"
            }
        },
        {
            name: "name",
            active: true,
            information: {
                description: "Computationally friendly name of the concept map",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/conformance-name"
            }
        },
        {
            name: "title",
            active: true,
            information: {
                description: "The human-friendly name of the concept map",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/conformance-title"
            }
        },
        {
            name: "status",
            active: true,
            information: {
                description: "The current status of the concept map",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/conformance-status"
            }
        },
        {
            name: "date",
            active: true,
            information: {
                description: "The concept map publication date",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/conformance-date"
            }
        },
        {
            name: "publisher",
            active: true,
            information: {
                description: "Name of the publisher of the concept map",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/conformance-publisher"
            }
        },
        {
            name: "description",
            active: true,
            information: {
                description: "The description of the concept map",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/conformance-description"
            }
        },
        {
            name: "identifier",
            active: true,
            information: {
                description: "External identifier for the concept map",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/conformance-identifier"
            }
        },
        {
            name: "jurisdiction",
            active: true,
            information: {
                description: "Intended jurisdiction for the concept map",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/conformance-jurisdiction"
            }
        },
        {
            name: "context",
            active: true,
            information: {
                description: "A use context assigned to the concept map",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/conformance-context"
            }
        },
        {
            name: "context-type",
            active: true,
            information: {
                description: "A type of use context assigned to the concept map",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/conformance-context-type"
            }
        },
        {
            name: "context-quantity",
            active: true,
            information: {
                description: "A quantity- or range-valued use context assigned to the concept map",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/conformance-context-quantity"
            }
        },
        {
            name: "source",
            active: true,
            information: {
                description: "Canonical reference to the source of the concept map",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/ConceptMap-source"
            }
        },
        {
            name: "source-uri",
            active: true,
            information: {
                description: "The source value set that contains the concepts that are being mapped",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/ConceptMap-source-uri"
            }
        },
        {
            name: "source-system",
            active: true,
            information: {
                description: "Source system where concepts to be mapped are defined",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/ConceptMap-source-system"
            }
        },
        {
            name: "source-code",
            active: true,
            information: {
                description: "Identifies element being mapped",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/ConceptMap-source-code"
            }
        },
        {
            name: "target",
            active: true,
            information: {
                description: "Canonical reference to the target of the concept map",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/ConceptMap-target"
            }
        },
        {
            name: "target-uri",
            active: true,
            information: {
                description: "The target value set which provides context for the mappings",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/ConceptMap-target-uri"
            }
        },
        {
            name: "target-system",
            active: true,
            information: {
                description: "Target system that the concepts are to be mapped to",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/ConceptMap-target-system"
            }
        },
        {
            name: "target-code",
            active: true,
            information: {
                description: "Code in target system",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/ConceptMap-target-code"
            }
        },
        {
            name: "dependson",
            active: true,
            information: {
                description: "Reference to property mapping depends on",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/ConceptMap-dependson"
            }
        },
        {
            name: "product",
            active: true,
            information: {
                description: "Reference to property mapping",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/ConceptMap-product"
            }
        },
        {
            name: "other",
            active: true,
            information: {
                description: "Canonical reference to an additional ConceptMap to use for mapping if the source concept is unmapped",
                builtin: false,
                documentation: "http://hl7.org/fhir/SearchParameter/ConceptMap-other"
            }
        }
    ],
    operations: [
        {
            name: "translate",
            active: true,
            // TEMPORARY (api-conformance): tolerate unknown operation params (e.g. the
            // test runner's "uuid", or "sourceSystem"). See conformance_shim.bal.
            preProcessor: lenientOperationPreProcessor,
            parameters: [
                {
                    name: "url",
                    active: true,
                    min: 0
                },
                {
                    name: "conceptMap",
                    active: true,
                    min: 0
                },
                {
                    name: "conceptMapVersion",
                    active: true,
                    min: 0
                },
                {
                    name: "code",
                    active: true,
                    min: 0
                },
                {
                    name: "system",
                    active: true,
                    min: 0
                },
                {
                    name: "version",
                    active: true,
                    min: 0
                },
                {
                    name: "source",
                    active: true,
                    min: 0
                },
                {
                    name: "coding",
                    active: true,
                    min: 0
                },
                {
                    name: "codeableConcept",
                    active: true,
                    min: 0
                },
                {
                    name: "target",
                    active: true,
                    min: 0
                },
                {
                    name: "targetsystem",
                    active: true,
                    min: 0
                },
                {
                    name: "dependency",
                    active: true,
                    min: 0
                },
                {
                    name: "reverse",
                    active: true,
                    min: 0
                }
            ]
        },
        {
            name: "closure",
            active: true,
            parameters: [
                {
                    name: "name",
                    active: true,
                    min: 1
                },
                {
                    name: "concept",
                    active: true,
                    min: 0
                },
                {
                    name: "version",
                    active: true,
                    min: 0
                }
            ]
        }
    ],
    serverConfig: (),
    authzConfig: ()
};

