[package]
org = "wso2"
name = "FHIRPathService"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "FHIRPATH"]
version = "1.0.1"
distribution = "2201.8.4"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "health.fhir.r4utils.fhirpath"
version = "1.1.0"
