-- AUTO-GENERATED FILE.

-- This file is an auto-generated file by Ballerina persistence layer for model.
-- Please verify the generated scripts and execute them against the target DB server.

DROP TABLE IF EXISTS `TestScriptTable`;
DROP TABLE IF EXISTS `TestReportTable`;
DROP TABLE IF EXISTS `RelatedPersonTable`;
DROP TABLE IF EXISTS `EvidenceVariableTable`;
DROP TABLE IF EXISTS `ValueSetTable`;
DROP TABLE IF EXISTS `DocumentManifestTable`;
DROP TABLE IF EXISTS `ImmunizationRecommendationTable`;
DROP TABLE IF EXISTS `DeviceMetricTable`;
DROP TABLE IF EXISTS `LocationTable`;
DROP TABLE IF EXISTS `ExplanationOfBenefitTable`;
DROP TABLE IF EXISTS `FlagTable`;
DROP TABLE IF EXISTS `MedicationStatementTable`;
DROP TABLE IF EXISTS `InsurancePlanTable`;
DROP TABLE IF EXISTS `MedicinalProductContraindicationTable`;
DROP TABLE IF EXISTS `ClaimResponseTable`;
DROP TABLE IF EXISTS `MedicinalProductAuthorizationTable`;
DROP TABLE IF EXISTS `ImagingStudyTable`;
DROP TABLE IF EXISTS `PractitionerRoleTable`;
DROP TABLE IF EXISTS `GroupTable`;
DROP TABLE IF EXISTS `PersonTable`;
DROP TABLE IF EXISTS `PractitionerTable`;
DROP TABLE IF EXISTS `ActivityDefinitionTable`;
DROP TABLE IF EXISTS `EvidenceTable`;
DROP TABLE IF EXISTS `DeviceTable`;
DROP TABLE IF EXISTS `FamilyMemberHistoryTable`;
DROP TABLE IF EXISTS `AdverseEventTable`;
DROP TABLE IF EXISTS `SupplyRequestTable`;
DROP TABLE IF EXISTS `ExampleScenarioTable`;
DROP TABLE IF EXISTS `InvoiceTable`;
DROP TABLE IF EXISTS `QuestionnaireResponseTable`;
DROP TABLE IF EXISTS `ObservationTable`;
DROP TABLE IF EXISTS `EffectEvidenceSynthesisTable`;
DROP TABLE IF EXISTS `OperationDefinitionTable`;
DROP TABLE IF EXISTS `MeasureReportTable`;
DROP TABLE IF EXISTS `SupplyDeliveryTable`;
DROP TABLE IF EXISTS `ServiceRequestTable`;
DROP TABLE IF EXISTS `BasicTable`;
DROP TABLE IF EXISTS `SubscriptionTable`;
DROP TABLE IF EXISTS `EnrollmentResponseTable`;
DROP TABLE IF EXISTS `DeviceRequestTable`;
DROP TABLE IF EXISTS `AppointmentTable`;
DROP TABLE IF EXISTS `NamingSystemTable`;
DROP TABLE IF EXISTS `StructureDefinitionTable`;
DROP TABLE IF EXISTS `ClinicalImpressionTable`;
DROP TABLE IF EXISTS `CommunicationTable`;
DROP TABLE IF EXISTS `OrganizationTable`;
DROP TABLE IF EXISTS `CoverageEligibilityResponseTable`;
DROP TABLE IF EXISTS `ResearchStudyTable`;
DROP TABLE IF EXISTS `BundleTable`;
DROP TABLE IF EXISTS `EncounterTable`;
DROP TABLE IF EXISTS `RiskAssessmentTable`;
DROP TABLE IF EXISTS `ListTable`;
DROP TABLE IF EXISTS `OrganizationAffiliationTable`;
DROP TABLE IF EXISTS `SEARCH_PARAM_RES_EXPRESSIONS`;
DROP TABLE IF EXISTS `ChargeItemTable`;
DROP TABLE IF EXISTS `MedicationKnowledgeTable`;
DROP TABLE IF EXISTS `PlanDefinitionTable`;
DROP TABLE IF EXISTS `CarePlanTable`;
DROP TABLE IF EXISTS `VisionPrescriptionTable`;
DROP TABLE IF EXISTS `EpisodeOfCareTable`;
DROP TABLE IF EXISTS `CareTeamTable`;
DROP TABLE IF EXISTS `MedicationAdministrationTable`;
DROP TABLE IF EXISTS `ConsentTable`;
DROP TABLE IF EXISTS `DetectedIssueTable`;
DROP TABLE IF EXISTS `SubstanceSpecificationTable`;
DROP TABLE IF EXISTS `AllergyIntoleranceTable`;
DROP TABLE IF EXISTS `MedicinalProductIndicationTable`;
DROP TABLE IF EXISTS `MedicinalProductPharmaceuticalTable`;
DROP TABLE IF EXISTS `SlotTable`;
DROP TABLE IF EXISTS `VerificationResultTable`;
DROP TABLE IF EXISTS `SpecimenTable`;
DROP TABLE IF EXISTS `ResearchSubjectTable`;
DROP TABLE IF EXISTS `MedicationTable`;
DROP TABLE IF EXISTS `ResearchDefinitionTable`;
DROP TABLE IF EXISTS `HealthcareServiceTable`;
DROP TABLE IF EXISTS `PaymentNoticeTable`;
DROP TABLE IF EXISTS `ProvenanceTable`;
DROP TABLE IF EXISTS `GraphDefinitionTable`;
DROP TABLE IF EXISTS `MediaTable`;
DROP TABLE IF EXISTS `BodyStructureTable`;
DROP TABLE IF EXISTS `DiagnosticReportTable`;
DROP TABLE IF EXISTS `GoalTable`;
DROP TABLE IF EXISTS `CapabilityStatementTable`;
DROP TABLE IF EXISTS `DeviceUseStatementTable`;
DROP TABLE IF EXISTS `ScheduleTable`;
DROP TABLE IF EXISTS `MedicinalProductPackagedTable`;
DROP TABLE IF EXISTS `ProcedureTable`;
DROP TABLE IF EXISTS `LibraryTable`;
DROP TABLE IF EXISTS `CodeSystemTable`;
DROP TABLE IF EXISTS `CommunicationRequestTable`;
DROP TABLE IF EXISTS `DocumentReferenceTable`;
DROP TABLE IF EXISTS `RequestGroupTable`;
DROP TABLE IF EXISTS `ClaimTable`;
DROP TABLE IF EXISTS `MessageDefinitionTable`;
DROP TABLE IF EXISTS `RiskEvidenceSynthesisTable`;
DROP TABLE IF EXISTS `TaskTable`;
DROP TABLE IF EXISTS `ImplementationGuideTable`;
DROP TABLE IF EXISTS `StructureMapTable`;
DROP TABLE IF EXISTS `MedicinalProductUndesirableEffectTable`;
DROP TABLE IF EXISTS `CompartmentDefinitionTable`;
DROP TABLE IF EXISTS `EndpointTable`;
DROP TABLE IF EXISTS `TerminologyCapabilitiesTable`;
DROP TABLE IF EXISTS `ConditionTable`;
DROP TABLE IF EXISTS `CompositionTable`;
DROP TABLE IF EXISTS `ContractTable`;
DROP TABLE IF EXISTS `ImmunizationTable`;
DROP TABLE IF EXISTS `MedicationDispenseTable`;
DROP TABLE IF EXISTS `MolecularSequenceTable`;
DROP TABLE IF EXISTS `SearchParameterTable`;
DROP TABLE IF EXISTS `MedicationRequestTable`;
DROP TABLE IF EXISTS `EnrollmentRequestTable`;
DROP TABLE IF EXISTS `SpecimenDefinitionTable`;
DROP TABLE IF EXISTS `EventDefinitionTable`;
DROP TABLE IF EXISTS `ImmunizationEvaluationTable`;
DROP TABLE IF EXISTS `PaymentReconciliationTable`;
DROP TABLE IF EXISTS `MeasureTable`;
DROP TABLE IF EXISTS `ConceptMapTable`;
DROP TABLE IF EXISTS `ResearchElementDefinitionTable`;
DROP TABLE IF EXISTS `GuidanceResponseTable`;
DROP TABLE IF EXISTS `LinkageTable`;
DROP TABLE IF EXISTS `MedicinalProductTable`;
DROP TABLE IF EXISTS `DeviceDefinitionTable`;
DROP TABLE IF EXISTS `CoverageEligibilityRequestTable`;
DROP TABLE IF EXISTS `PatientTable`;
DROP TABLE IF EXISTS `CoverageTable`;
DROP TABLE IF EXISTS `SubstanceTable`;
DROP TABLE IF EXISTS `ChargeItemDefinitionTable`;
DROP TABLE IF EXISTS `MedicinalProductInteractionTable`;
DROP TABLE IF EXISTS `AccountTable`;
DROP TABLE IF EXISTS `MessageHeaderTable`;
DROP TABLE IF EXISTS `AuditEventTable`;
DROP TABLE IF EXISTS `NutritionOrderTable`;
DROP TABLE IF EXISTS `QuestionnaireTable`;
DROP TABLE IF EXISTS `REFERENCES`;
DROP TABLE IF EXISTS `AppointmentResponseTable`;

CREATE TABLE `AppointmentResponseTable` (
	`APPOINTMENTRESPONSETABLE_ID` VARCHAR(191) NOT NULL,
	`PART_STATUS` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`APPOINTMENTRESPONSETABLE_ID`)
);

CREATE TABLE `REFERENCES` (
	`ID` INT AUTO_INCREMENT,
	`SOURCE_RESOURCE_TYPE` VARCHAR(191) NOT NULL,
	`SOURCE_RESOURCE_ID` VARCHAR(191) NOT NULL,
	`SOURCE_EXPRESSION` VARCHAR(191) NOT NULL,
	`TARGET_RESOURCE_TYPE` VARCHAR(191) NOT NULL,
	`TARGET_RESOURCE_ID` VARCHAR(191) NOT NULL,
	`DISPLAY_VALUE` VARCHAR(191) NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	PRIMARY KEY(`ID`)
);

CREATE TABLE `QuestionnaireTable` (
	`QUESTIONNAIRETABLE_ID` VARCHAR(191) NOT NULL,
	`DEFINITION` VARCHAR(512),
	`PUBLISHER` VARCHAR(512),
	`JURISDICTION` VARCHAR(2048),
	`SUBJECT_TYPE` VARCHAR(2048),
	`EFFECTIVE` DATE,
	`CONTEXT` VARCHAR(2048),
	`URL` VARCHAR(512),
	`NAME` VARCHAR(512),
	`DATE` DATE,
	`CODE` VARCHAR(2048),
	`STATUS` VARCHAR(2048),
	`DESCRIPTION` VARCHAR(512),
	`VERSION` VARCHAR(2048),
	`TITLE` VARCHAR(512),
	`IDENTIFIER` VARCHAR(2048),
	`CONTEXT_QUANTITY` VARCHAR(2048),
	`CONTEXT_TYPE` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`QUESTIONNAIRETABLE_ID`)
);

CREATE TABLE `NutritionOrderTable` (
	`NUTRITIONORDERTABLE_ID` VARCHAR(191) NOT NULL,
	`SUPPLEMENT` VARCHAR(2048),
	`STATUS` VARCHAR(2048),
	`DATETIME` DATE,
	`INSTANTIATES_URI` VARCHAR(512),
	`ADDITIVE` VARCHAR(2048),
	`ORALDIET` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`FORMULA` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`NUTRITIONORDERTABLE_ID`)
);

CREATE TABLE `AuditEventTable` (
	`AUDITEVENTTABLE_ID` VARCHAR(191) NOT NULL,
	`SUBTYPE` VARCHAR(2048),
	`SITE` VARCHAR(2048),
	`OUTCOME` VARCHAR(2048),
	`ENTITY_ROLE` VARCHAR(2048),
	`AGENT_NAME` VARCHAR(512),
	`ENTITY_TYPE` VARCHAR(2048),
	`DATE` DATE,
	`POLICY` VARCHAR(512),
	`ALTID` VARCHAR(2048),
	`ACTION` VARCHAR(2048),
	`ADDRESS` VARCHAR(512),
	`TYPE` VARCHAR(2048),
	`ENTITY_NAME` VARCHAR(512),
	`AGENT_ROLE` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`AUDITEVENTTABLE_ID`)
);

CREATE TABLE `MessageHeaderTable` (
	`MESSAGEHEADERTABLE_ID` VARCHAR(191) NOT NULL,
	`CODE` VARCHAR(2048),
	`SOURCE_URI` VARCHAR(512),
	`DESTINATION` VARCHAR(512),
	`DESTINATION_URI` VARCHAR(512),
	`SOURCE` VARCHAR(512),
	`RESPONSE_ID` VARCHAR(2048),
	`EVENT` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`MESSAGEHEADERTABLE_ID`)
);

CREATE TABLE `AccountTable` (
	`ACCOUNTTABLE_ID` VARCHAR(191) NOT NULL,
	`STATUS` VARCHAR(2048),
	`PERIOD` DATE,
	`IDENTIFIER` VARCHAR(2048),
	`TYPE` VARCHAR(2048),
	`NAME` VARCHAR(512),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`ACCOUNTTABLE_ID`)
);

CREATE TABLE `MedicinalProductInteractionTable` (
	`MEDICINALPRODUCTINTERACTIONTABLE_ID` VARCHAR(191) NOT NULL,
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`MEDICINALPRODUCTINTERACTIONTABLE_ID`)
);

CREATE TABLE `ChargeItemDefinitionTable` (
	`CHARGEITEMDEFINITIONTABLE_ID` VARCHAR(191) NOT NULL,
	`PUBLISHER` VARCHAR(512),
	`JURISDICTION` VARCHAR(2048),
	`EFFECTIVE` DATE,
	`CONTEXT` VARCHAR(2048),
	`URL` VARCHAR(512),
	`DATE` DATE,
	`STATUS` VARCHAR(2048),
	`DESCRIPTION` VARCHAR(512),
	`VERSION` VARCHAR(2048),
	`TITLE` VARCHAR(512),
	`IDENTIFIER` VARCHAR(2048),
	`CONTEXT_QUANTITY` VARCHAR(2048),
	`CONTEXT_TYPE` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`CHARGEITEMDEFINITIONTABLE_ID`)
);

CREATE TABLE `SubstanceTable` (
	`SUBSTANCETABLE_ID` VARCHAR(191) NOT NULL,
	`CONTAINER_IDENTIFIER` VARCHAR(2048),
	`CODE` VARCHAR(2048),
	`STATUS` VARCHAR(2048),
	`QUANTITY` VARCHAR(2048),
	`CATEGORY` VARCHAR(2048),
	`EXPIRY` DATE,
	`IDENTIFIER` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`SUBSTANCETABLE_ID`)
);

CREATE TABLE `CoverageTable` (
	`COVERAGETABLE_ID` VARCHAR(191) NOT NULL,
	`STATUS` VARCHAR(2048),
	`DEPENDENT` VARCHAR(512),
	`IDENTIFIER` VARCHAR(2048),
	`CLASS_VALUE` VARCHAR(512),
	`TYPE` VARCHAR(2048),
	`CLASS_TYPE` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`COVERAGETABLE_ID`)
);

CREATE TABLE `PatientTable` (
	`PATIENTTABLE_ID` VARCHAR(191) NOT NULL,
	`LANGUAGE` VARCHAR(2048),
	`ADDRESS_COUNTRY` VARCHAR(512),
	`ADDRESS_POSTALCODE` VARCHAR(512),
	`ACTIVE` VARCHAR(2048),
	`PHONE` VARCHAR(2048),
	`DECEASED` VARCHAR(2048),
	`BIRTHDATE` DATE,
	`ADDRESS_CITY` VARCHAR(512),
	`EMAIL` VARCHAR(2048),
	`ADDRESS_STATE` VARCHAR(512),
	`TELECOM` VARCHAR(2048),
	`NAME` VARCHAR(512),
	`FAMILY` VARCHAR(512),
	`ADDRESS_USE` VARCHAR(2048),
	`GIVEN` VARCHAR(512),
	`ADDRESS` VARCHAR(512),
	`GENDER` VARCHAR(2048),
	`PHONETIC` VARCHAR(512),
	`DEATH_DATE` DATE,
	`IDENTIFIER` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`PATIENTTABLE_ID`)
);

CREATE TABLE `CoverageEligibilityRequestTable` (
	`COVERAGEELIGIBILITYREQUESTTABLE_ID` VARCHAR(191) NOT NULL,
	`CREATED` DATE,
	`STATUS` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`COVERAGEELIGIBILITYREQUESTTABLE_ID`)
);

CREATE TABLE `DeviceDefinitionTable` (
	`DEVICEDEFINITIONTABLE_ID` VARCHAR(191) NOT NULL,
	`IDENTIFIER` VARCHAR(2048),
	`TYPE` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`DEVICEDEFINITIONTABLE_ID`)
);

CREATE TABLE `MedicinalProductTable` (
	`MEDICINALPRODUCTTABLE_ID` VARCHAR(191) NOT NULL,
	`NAME_LANGUAGE` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`NAME` VARCHAR(512),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`MEDICINALPRODUCTTABLE_ID`)
);

CREATE TABLE `LinkageTable` (
	`LINKAGETABLE_ID` VARCHAR(191) NOT NULL,
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`LINKAGETABLE_ID`)
);

CREATE TABLE `GuidanceResponseTable` (
	`GUIDANCERESPONSETABLE_ID` VARCHAR(191) NOT NULL,
	`REQUEST` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`GUIDANCERESPONSETABLE_ID`)
);

CREATE TABLE `ResearchElementDefinitionTable` (
	`RESEARCHELEMENTDEFINITIONTABLE_ID` VARCHAR(191) NOT NULL,
	`PUBLISHER` VARCHAR(512),
	`JURISDICTION` VARCHAR(2048),
	`EFFECTIVE` DATE,
	`TOPIC` VARCHAR(2048),
	`CONTEXT` VARCHAR(2048),
	`URL` VARCHAR(512),
	`NAME` VARCHAR(512),
	`DATE` DATE,
	`STATUS` VARCHAR(2048),
	`DESCRIPTION` VARCHAR(512),
	`VERSION` VARCHAR(2048),
	`TITLE` VARCHAR(512),
	`IDENTIFIER` VARCHAR(2048),
	`CONTEXT_QUANTITY` VARCHAR(2048),
	`CONTEXT_TYPE` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`RESEARCHELEMENTDEFINITIONTABLE_ID`)
);

CREATE TABLE `ConceptMapTable` (
	`CONCEPTMAPTABLE_ID` VARCHAR(191) NOT NULL,
	`PUBLISHER` VARCHAR(512),
	`JURISDICTION` VARCHAR(2048),
	`CONTEXT` VARCHAR(2048),
	`URL` VARCHAR(512),
	`SOURCE_SYSTEM` VARCHAR(512),
	`NAME` VARCHAR(512),
	`DATE` DATE,
	`TARGET_SYSTEM` VARCHAR(512),
	`SOURCE_CODE` VARCHAR(2048),
	`STATUS` VARCHAR(2048),
	`DESCRIPTION` VARCHAR(512),
	`TARGET_CODE` VARCHAR(2048),
	`PRODUCT` VARCHAR(512),
	`VERSION` VARCHAR(2048),
	`TITLE` VARCHAR(512),
	`CONTEXT_QUANTITY` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`DEPENDSON` VARCHAR(512),
	`CONTEXT_TYPE` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`CONCEPTMAPTABLE_ID`)
);

CREATE TABLE `MeasureTable` (
	`MEASURETABLE_ID` VARCHAR(191) NOT NULL,
	`PUBLISHER` VARCHAR(512),
	`JURISDICTION` VARCHAR(2048),
	`EFFECTIVE` DATE,
	`TOPIC` VARCHAR(2048),
	`CONTEXT` VARCHAR(2048),
	`URL` VARCHAR(512),
	`NAME` VARCHAR(512),
	`DATE` DATE,
	`STATUS` VARCHAR(2048),
	`DESCRIPTION` VARCHAR(512),
	`VERSION` VARCHAR(2048),
	`TITLE` VARCHAR(512),
	`IDENTIFIER` VARCHAR(2048),
	`CONTEXT_QUANTITY` VARCHAR(2048),
	`CONTEXT_TYPE` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`MEASURETABLE_ID`)
);

CREATE TABLE `PaymentReconciliationTable` (
	`PAYMENTRECONCILIATIONTABLE_ID` VARCHAR(191) NOT NULL,
	`CREATED` DATE,
	`STATUS` VARCHAR(2048),
	`OUTCOME` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`DISPOSITION` VARCHAR(512),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`PAYMENTRECONCILIATIONTABLE_ID`)
);

CREATE TABLE `ImmunizationEvaluationTable` (
	`IMMUNIZATIONEVALUATIONTABLE_ID` VARCHAR(191) NOT NULL,
	`DATE` DATE,
	`STATUS` VARCHAR(2048),
	`TARGET_DISEASE` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`DOSE_STATUS` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`IMMUNIZATIONEVALUATIONTABLE_ID`)
);

CREATE TABLE `EventDefinitionTable` (
	`EVENTDEFINITIONTABLE_ID` VARCHAR(191) NOT NULL,
	`PUBLISHER` VARCHAR(512),
	`JURISDICTION` VARCHAR(2048),
	`EFFECTIVE` DATE,
	`TOPIC` VARCHAR(2048),
	`CONTEXT` VARCHAR(2048),
	`URL` VARCHAR(512),
	`NAME` VARCHAR(512),
	`DATE` DATE,
	`STATUS` VARCHAR(2048),
	`DESCRIPTION` VARCHAR(512),
	`VERSION` VARCHAR(2048),
	`TITLE` VARCHAR(512),
	`IDENTIFIER` VARCHAR(2048),
	`CONTEXT_QUANTITY` VARCHAR(2048),
	`CONTEXT_TYPE` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`EVENTDEFINITIONTABLE_ID`)
);

CREATE TABLE `SpecimenDefinitionTable` (
	`SPECIMENDEFINITIONTABLE_ID` VARCHAR(191) NOT NULL,
	`CONTAINER` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`TYPE` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`SPECIMENDEFINITIONTABLE_ID`)
);

CREATE TABLE `EnrollmentRequestTable` (
	`ENROLLMENTREQUESTTABLE_ID` VARCHAR(191) NOT NULL,
	`STATUS` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`ENROLLMENTREQUESTTABLE_ID`)
);

CREATE TABLE `MedicationRequestTable` (
	`MEDICATIONREQUESTTABLE_ID` VARCHAR(191) NOT NULL,
	`DATE` DATE,
	`CODE` VARCHAR(2048),
	`STATUS` VARCHAR(2048),
	`CATEGORY` VARCHAR(2048),
	`INTENT` VARCHAR(2048),
	`PRIORITY` VARCHAR(2048),
	`INTENDED_PERFORMERTYPE` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`AUTHOREDON` DATE,
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`MEDICATIONREQUESTTABLE_ID`)
);

CREATE TABLE `SearchParameterTable` (
	`SEARCHPARAMETERTABLE_ID` VARCHAR(191) NOT NULL,
	`TARGET` VARCHAR(2048),
	`PUBLISHER` VARCHAR(512),
	`JURISDICTION` VARCHAR(2048),
	`CONTEXT` VARCHAR(2048),
	`URL` VARCHAR(512),
	`NAME` VARCHAR(512),
	`BASE` VARCHAR(2048),
	`DATE` DATE,
	`CODE` VARCHAR(2048),
	`STATUS` VARCHAR(2048),
	`DESCRIPTION` VARCHAR(512),
	`VERSION` VARCHAR(2048),
	`CONTEXT_QUANTITY` VARCHAR(2048),
	`TYPE` VARCHAR(2048),
	`CONTEXT_TYPE` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`SEARCHPARAMETERTABLE_ID`)
);

CREATE TABLE `MolecularSequenceTable` (
	`MOLECULARSEQUENCETABLE_ID` VARCHAR(191) NOT NULL,
	`CHROMOSOME` VARCHAR(2048),
	`VARIANT_START` INT,
	`WINDOW_START` INT,
	`VARIANT_END` INT,
	`REFERENCESEQID` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`WINDOW_END` INT,
	`TYPE` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`MOLECULARSEQUENCETABLE_ID`)
);

CREATE TABLE `MedicationDispenseTable` (
	`MEDICATIONDISPENSETABLE_ID` VARCHAR(191) NOT NULL,
	`CODE` VARCHAR(2048),
	`STATUS` VARCHAR(2048),
	`WHENHANDEDOVER` DATE,
	`IDENTIFIER` VARCHAR(2048),
	`TYPE` VARCHAR(2048),
	`WHENPREPARED` DATE,
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`MEDICATIONDISPENSETABLE_ID`)
);

CREATE TABLE `ImmunizationTable` (
	`IMMUNIZATIONTABLE_ID` VARCHAR(191) NOT NULL,
	`DATE` DATE,
	`VACCINE_CODE` VARCHAR(2048),
	`STATUS` VARCHAR(2048),
	`STATUS_REASON` VARCHAR(2048),
	`SERIES` VARCHAR(512),
	`TARGET_DISEASE` VARCHAR(2048),
	`REASON_CODE` VARCHAR(2048),
	`REACTION_DATE` DATE,
	`IDENTIFIER` VARCHAR(2048),
	`LOT_NUMBER` VARCHAR(512),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`IMMUNIZATIONTABLE_ID`)
);

CREATE TABLE `ContractTable` (
	`CONTRACTTABLE_ID` VARCHAR(191) NOT NULL,
	`ISSUED` DATE,
	`STATUS` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`INSTANTIATES` VARCHAR(512),
	`URL` VARCHAR(512),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`CONTRACTTABLE_ID`)
);

CREATE TABLE `CompositionTable` (
	`COMPOSITIONTABLE_ID` VARCHAR(191) NOT NULL,
	`DATE` DATE,
	`STATUS` VARCHAR(2048),
	`RELATED_ID` VARCHAR(2048),
	`CATEGORY` VARCHAR(2048),
	`PERIOD` DATE,
	`TITLE` VARCHAR(512),
	`IDENTIFIER` VARCHAR(2048),
	`TYPE` VARCHAR(2048),
	`CONTEXT` VARCHAR(2048),
	`CONFIDENTIALITY` VARCHAR(2048),
	`SECTION` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`COMPOSITIONTABLE_ID`)
);

CREATE TABLE `ConditionTable` (
	`CONDITIONTABLE_ID` VARCHAR(191) NOT NULL,
	`CLINICAL_STATUS` VARCHAR(2048),
	`STAGE` VARCHAR(2048),
	`ONSET_AGE` VARCHAR(2048),
	`ONSET_INFO` VARCHAR(512),
	`EVIDENCE` VARCHAR(2048),
	`ONSET_DATE` DATE,
	`BODY_SITE` VARCHAR(2048),
	`VERIFICATION_STATUS` VARCHAR(2048),
	`CODE` VARCHAR(2048),
	`ABATEMENT_AGE` VARCHAR(2048),
	`ABATEMENT_STRING` VARCHAR(512),
	`RECORDED_DATE` DATE,
	`CATEGORY` VARCHAR(2048),
	`ABATEMENT_DATE` DATE,
	`IDENTIFIER` VARCHAR(2048),
	`SEVERITY` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`CONDITIONTABLE_ID`)
);

CREATE TABLE `TerminologyCapabilitiesTable` (
	`TERMINOLOGYCAPABILITIESTABLE_ID` VARCHAR(191) NOT NULL,
	`DATE` DATE,
	`PUBLISHER` VARCHAR(512),
	`STATUS` VARCHAR(2048),
	`JURISDICTION` VARCHAR(2048),
	`DESCRIPTION` VARCHAR(512),
	`VERSION` VARCHAR(2048),
	`TITLE` VARCHAR(512),
	`CONTEXT_QUANTITY` VARCHAR(2048),
	`CONTEXT` VARCHAR(2048),
	`URL` VARCHAR(512),
	`CONTEXT_TYPE` VARCHAR(2048),
	`NAME` VARCHAR(512),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`TERMINOLOGYCAPABILITIESTABLE_ID`)
);

CREATE TABLE `EndpointTable` (
	`ENDPOINTTABLE_ID` VARCHAR(191) NOT NULL,
	`CONNECTION_TYPE` VARCHAR(2048),
	`STATUS` VARCHAR(2048),
	`PAYLOAD_TYPE` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`NAME` VARCHAR(512),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`ENDPOINTTABLE_ID`)
);

CREATE TABLE `CompartmentDefinitionTable` (
	`COMPARTMENTDEFINITIONTABLE_ID` VARCHAR(191) NOT NULL,
	`DATE` DATE,
	`PUBLISHER` VARCHAR(512),
	`CODE` VARCHAR(2048),
	`STATUS` VARCHAR(2048),
	`DESCRIPTION` VARCHAR(512),
	`VERSION` VARCHAR(2048),
	`CONTEXT_QUANTITY` VARCHAR(2048),
	`CONTEXT` VARCHAR(2048),
	`URL` VARCHAR(512),
	`RESOURCE` VARCHAR(2048),
	`CONTEXT_TYPE` VARCHAR(2048),
	`NAME` VARCHAR(512),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`COMPARTMENTDEFINITIONTABLE_ID`)
);

CREATE TABLE `MedicinalProductUndesirableEffectTable` (
	`MEDICINALPRODUCTUNDESIRABLEEFFECTTABLE_ID` VARCHAR(191) NOT NULL,
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`MEDICINALPRODUCTUNDESIRABLEEFFECTTABLE_ID`)
);

CREATE TABLE `StructureMapTable` (
	`STRUCTUREMAPTABLE_ID` VARCHAR(191) NOT NULL,
	`PUBLISHER` VARCHAR(512),
	`JURISDICTION` VARCHAR(2048),
	`CONTEXT` VARCHAR(2048),
	`URL` VARCHAR(512),
	`NAME` VARCHAR(512),
	`DATE` DATE,
	`STATUS` VARCHAR(2048),
	`DESCRIPTION` VARCHAR(512),
	`VERSION` VARCHAR(2048),
	`TITLE` VARCHAR(512),
	`IDENTIFIER` VARCHAR(2048),
	`CONTEXT_QUANTITY` VARCHAR(2048),
	`CONTEXT_TYPE` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`STRUCTUREMAPTABLE_ID`)
);

CREATE TABLE `ImplementationGuideTable` (
	`IMPLEMENTATIONGUIDETABLE_ID` VARCHAR(191) NOT NULL,
	`PUBLISHER` VARCHAR(512),
	`JURISDICTION` VARCHAR(2048),
	`EXPERIMENTAL` VARCHAR(2048),
	`CONTEXT` VARCHAR(2048),
	`URL` VARCHAR(512),
	`NAME` VARCHAR(512),
	`DATE` DATE,
	`STATUS` VARCHAR(2048),
	`DESCRIPTION` VARCHAR(512),
	`VERSION` VARCHAR(2048),
	`TITLE` VARCHAR(512),
	`CONTEXT_QUANTITY` VARCHAR(2048),
	`CONTEXT_TYPE` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`IMPLEMENTATIONGUIDETABLE_ID`)
);

CREATE TABLE `TaskTable` (
	`TASKTABLE_ID` VARCHAR(191) NOT NULL,
	`CODE` VARCHAR(2048),
	`STATUS` VARCHAR(2048),
	`BUSINESS_STATUS` VARCHAR(2048),
	`PERIOD` DATE,
	`AUTHORED_ON` DATE,
	`INTENT` VARCHAR(2048),
	`PRIORITY` VARCHAR(2048),
	`GROUP_IDENTIFIER` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`PERFORMER` VARCHAR(2048),
	`MODIFIED` DATE,
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`TASKTABLE_ID`)
);

CREATE TABLE `RiskEvidenceSynthesisTable` (
	`RISKEVIDENCESYNTHESISTABLE_ID` VARCHAR(191) NOT NULL,
	`PUBLISHER` VARCHAR(512),
	`JURISDICTION` VARCHAR(2048),
	`EFFECTIVE` DATE,
	`CONTEXT` VARCHAR(2048),
	`URL` VARCHAR(512),
	`NAME` VARCHAR(512),
	`DATE` DATE,
	`STATUS` VARCHAR(2048),
	`DESCRIPTION` VARCHAR(512),
	`VERSION` VARCHAR(2048),
	`TITLE` VARCHAR(512),
	`IDENTIFIER` VARCHAR(2048),
	`CONTEXT_QUANTITY` VARCHAR(2048),
	`CONTEXT_TYPE` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`RISKEVIDENCESYNTHESISTABLE_ID`)
);

CREATE TABLE `MessageDefinitionTable` (
	`MESSAGEDEFINITIONTABLE_ID` VARCHAR(191) NOT NULL,
	`PUBLISHER` VARCHAR(512),
	`JURISDICTION` VARCHAR(2048),
	`FOCUS` VARCHAR(2048),
	`CONTEXT` VARCHAR(2048),
	`URL` VARCHAR(512),
	`EVENT` VARCHAR(2048),
	`NAME` VARCHAR(512),
	`DATE` DATE,
	`STATUS` VARCHAR(2048),
	`DESCRIPTION` VARCHAR(512),
	`CATEGORY` VARCHAR(2048),
	`VERSION` VARCHAR(2048),
	`TITLE` VARCHAR(512),
	`IDENTIFIER` VARCHAR(2048),
	`CONTEXT_QUANTITY` VARCHAR(2048),
	`CONTEXT_TYPE` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`MESSAGEDEFINITIONTABLE_ID`)
);

CREATE TABLE `ClaimTable` (
	`CLAIMTABLE_ID` VARCHAR(191) NOT NULL,
	`CREATED` DATE,
	`STATUS` VARCHAR(2048),
	`USE` VARCHAR(2048),
	`PRIORITY` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`CLAIMTABLE_ID`)
);

CREATE TABLE `RequestGroupTable` (
	`REQUESTGROUPTABLE_ID` VARCHAR(191) NOT NULL,
	`CODE` VARCHAR(2048),
	`STATUS` VARCHAR(2048),
	`INSTANTIATES_URI` VARCHAR(512),
	`INTENT` VARCHAR(2048),
	`AUTHORED` DATE,
	`PRIORITY` VARCHAR(2048),
	`GROUP_IDENTIFIER` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`REQUESTGROUPTABLE_ID`)
);

CREATE TABLE `DocumentReferenceTable` (
	`DOCUMENTREFERENCETABLE_ID` VARCHAR(191) NOT NULL,
	`LANGUAGE` VARCHAR(2048),
	`LOCATION` VARCHAR(512),
	`CONTENTTYPE` VARCHAR(2048),
	`RELATION` VARCHAR(2048),
	`FORMAT` VARCHAR(2048),
	`FACILITY` VARCHAR(2048),
	`EVENT` VARCHAR(2048),
	`DATE` DATE,
	`SECURITY_LABEL` VARCHAR(2048),
	`STATUS` VARCHAR(2048),
	`DESCRIPTION` VARCHAR(512),
	`CATEGORY` VARCHAR(2048),
	`PERIOD` DATE,
	`SETTING` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`TYPE` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`DOCUMENTREFERENCETABLE_ID`)
);

CREATE TABLE `CommunicationRequestTable` (
	`COMMUNICATIONREQUESTTABLE_ID` VARCHAR(191) NOT NULL,
	`STATUS` VARCHAR(2048),
	`MEDIUM` VARCHAR(2048),
	`OCCURRENCE` DATE,
	`CATEGORY` VARCHAR(2048),
	`AUTHORED` DATE,
	`PRIORITY` VARCHAR(2048),
	`GROUP_IDENTIFIER` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`COMMUNICATIONREQUESTTABLE_ID`)
);

CREATE TABLE `CodeSystemTable` (
	`CODESYSTEMTABLE_ID` VARCHAR(191) NOT NULL,
	`LANGUAGE` VARCHAR(2048),
	`SYSTEM` VARCHAR(512),
	`PUBLISHER` VARCHAR(512),
	`JURISDICTION` VARCHAR(2048),
	`CONTEXT` VARCHAR(2048),
	`URL` VARCHAR(512),
	`NAME` VARCHAR(512),
	`DATE` DATE,
	`CODE` VARCHAR(2048),
	`STATUS` VARCHAR(2048),
	`DESCRIPTION` VARCHAR(512),
	`VERSION` VARCHAR(2048),
	`CONTENT_MODE` VARCHAR(2048),
	`TITLE` VARCHAR(512),
	`IDENTIFIER` VARCHAR(2048),
	`CONTEXT_QUANTITY` VARCHAR(2048),
	`CONTEXT_TYPE` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`CODESYSTEMTABLE_ID`)
);

CREATE TABLE `LibraryTable` (
	`LIBRARYTABLE_ID` VARCHAR(191) NOT NULL,
	`PUBLISHER` VARCHAR(512),
	`JURISDICTION` VARCHAR(2048),
	`EFFECTIVE` DATE,
	`TOPIC` VARCHAR(2048),
	`CONTEXT` VARCHAR(2048),
	`URL` VARCHAR(512),
	`NAME` VARCHAR(512),
	`DATE` DATE,
	`STATUS` VARCHAR(2048),
	`DESCRIPTION` VARCHAR(512),
	`CONTENT_TYPE` VARCHAR(2048),
	`VERSION` VARCHAR(2048),
	`TITLE` VARCHAR(512),
	`IDENTIFIER` VARCHAR(2048),
	`CONTEXT_QUANTITY` VARCHAR(2048),
	`TYPE` VARCHAR(2048),
	`CONTEXT_TYPE` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`LIBRARYTABLE_ID`)
);

CREATE TABLE `ProcedureTable` (
	`PROCEDURETABLE_ID` VARCHAR(191) NOT NULL,
	`DATE` DATE,
	`CODE` VARCHAR(2048),
	`STATUS` VARCHAR(2048),
	`INSTANTIATES_URI` VARCHAR(512),
	`CATEGORY` VARCHAR(2048),
	`REASON_CODE` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`PROCEDURETABLE_ID`)
);

CREATE TABLE `MedicinalProductPackagedTable` (
	`MEDICINALPRODUCTPACKAGEDTABLE_ID` VARCHAR(191) NOT NULL,
	`IDENTIFIER` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`MEDICINALPRODUCTPACKAGEDTABLE_ID`)
);

CREATE TABLE `ScheduleTable` (
	`SCHEDULETABLE_ID` VARCHAR(191) NOT NULL,
	`DATE` DATE,
	`SERVICE_CATEGORY` VARCHAR(2048),
	`ACTIVE` VARCHAR(2048),
	`SPECIALTY` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`SERVICE_TYPE` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`SCHEDULETABLE_ID`)
);

CREATE TABLE `DeviceUseStatementTable` (
	`DEVICEUSESTATEMENTTABLE_ID` VARCHAR(191) NOT NULL,
	`IDENTIFIER` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`DEVICEUSESTATEMENTTABLE_ID`)
);

CREATE TABLE `CapabilityStatementTable` (
	`CAPABILITYSTATEMENTTABLE_ID` VARCHAR(191) NOT NULL,
	`PUBLISHER` VARCHAR(512),
	`JURISDICTION` VARCHAR(2048),
	`FORMAT` VARCHAR(2048),
	`MODE` VARCHAR(2048),
	`SECURITY_SERVICE` VARCHAR(2048),
	`CONTEXT` VARCHAR(2048),
	`SOFTWARE` VARCHAR(512),
	`URL` VARCHAR(512),
	`NAME` VARCHAR(512),
	`DATE` DATE,
	`STATUS` VARCHAR(2048),
	`DESCRIPTION` VARCHAR(512),
	`FHIRVERSION` VARCHAR(2048),
	`VERSION` VARCHAR(2048),
	`TITLE` VARCHAR(512),
	`CONTEXT_QUANTITY` VARCHAR(2048),
	`RESOURCE` VARCHAR(2048),
	`CONTEXT_TYPE` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`CAPABILITYSTATEMENTTABLE_ID`)
);

CREATE TABLE `GoalTable` (
	`GOALTABLE_ID` VARCHAR(191) NOT NULL,
	`TARGET_DATE` DATE,
	`ACHIEVEMENT_STATUS` VARCHAR(2048),
	`CATEGORY` VARCHAR(2048),
	`LIFECYCLE_STATUS` VARCHAR(2048),
	`START_DATE` DATE,
	`IDENTIFIER` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`GOALTABLE_ID`)
);

CREATE TABLE `DiagnosticReportTable` (
	`DIAGNOSTICREPORTTABLE_ID` VARCHAR(191) NOT NULL,
	`DATE` DATE,
	`ISSUED` DATE,
	`CODE` VARCHAR(2048),
	`STATUS` VARCHAR(2048),
	`CATEGORY` VARCHAR(2048),
	`CONCLUSION` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`DIAGNOSTICREPORTTABLE_ID`)
);

CREATE TABLE `BodyStructureTable` (
	`BODYSTRUCTURETABLE_ID` VARCHAR(191) NOT NULL,
	`LOCATION` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`MORPHOLOGY` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`BODYSTRUCTURETABLE_ID`)
);

CREATE TABLE `MediaTable` (
	`MEDIATABLE_ID` VARCHAR(191) NOT NULL,
	`SITE` VARCHAR(2048),
	`CREATED` DATE,
	`STATUS` VARCHAR(2048),
	`MODALITY` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`TYPE` VARCHAR(2048),
	`VIEW` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`MEDIATABLE_ID`)
);

CREATE TABLE `GraphDefinitionTable` (
	`GRAPHDEFINITIONTABLE_ID` VARCHAR(191) NOT NULL,
	`DATE` DATE,
	`PUBLISHER` VARCHAR(512),
	`STATUS` VARCHAR(2048),
	`JURISDICTION` VARCHAR(2048),
	`DESCRIPTION` VARCHAR(512),
	`VERSION` VARCHAR(2048),
	`START` VARCHAR(2048),
	`CONTEXT_QUANTITY` VARCHAR(2048),
	`CONTEXT` VARCHAR(2048),
	`URL` VARCHAR(512),
	`CONTEXT_TYPE` VARCHAR(2048),
	`NAME` VARCHAR(512),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`GRAPHDEFINITIONTABLE_ID`)
);

CREATE TABLE `ProvenanceTable` (
	`PROVENANCETABLE_ID` VARCHAR(191) NOT NULL,
	`RECORDED` DATE,
	`WHEN` DATE,
	`AGENT_TYPE` VARCHAR(2048),
	`SIGNATURE_TYPE` VARCHAR(2048),
	`AGENT_ROLE` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`PROVENANCETABLE_ID`)
);

CREATE TABLE `PaymentNoticeTable` (
	`PAYMENTNOTICETABLE_ID` VARCHAR(191) NOT NULL,
	`CREATED` DATE,
	`STATUS` VARCHAR(2048),
	`PAYMENT_STATUS` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`PAYMENTNOTICETABLE_ID`)
);

CREATE TABLE `HealthcareServiceTable` (
	`HEALTHCARESERVICETABLE_ID` VARCHAR(191) NOT NULL,
	`SERVICE_CATEGORY` VARCHAR(2048),
	`CHARACTERISTIC` VARCHAR(2048),
	`ACTIVE` VARCHAR(2048),
	`SPECIALTY` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`SERVICE_TYPE` VARCHAR(2048),
	`PROGRAM` VARCHAR(2048),
	`NAME` VARCHAR(512),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`HEALTHCARESERVICETABLE_ID`)
);

CREATE TABLE `ResearchDefinitionTable` (
	`RESEARCHDEFINITIONTABLE_ID` VARCHAR(191) NOT NULL,
	`PUBLISHER` VARCHAR(512),
	`JURISDICTION` VARCHAR(2048),
	`EFFECTIVE` DATE,
	`TOPIC` VARCHAR(2048),
	`CONTEXT` VARCHAR(2048),
	`URL` VARCHAR(512),
	`NAME` VARCHAR(512),
	`DATE` DATE,
	`STATUS` VARCHAR(2048),
	`DESCRIPTION` VARCHAR(512),
	`VERSION` VARCHAR(2048),
	`TITLE` VARCHAR(512),
	`IDENTIFIER` VARCHAR(2048),
	`CONTEXT_QUANTITY` VARCHAR(2048),
	`CONTEXT_TYPE` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`RESEARCHDEFINITIONTABLE_ID`)
);

CREATE TABLE `MedicationTable` (
	`MEDICATIONTABLE_ID` VARCHAR(191) NOT NULL,
	`CODE` VARCHAR(2048),
	`STATUS` VARCHAR(2048),
	`EXPIRATION_DATE` DATE,
	`FORM` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`LOT_NUMBER` VARCHAR(2048),
	`INGREDIENT_CODE` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`MEDICATIONTABLE_ID`)
);

CREATE TABLE `ResearchSubjectTable` (
	`RESEARCHSUBJECTTABLE_ID` VARCHAR(191) NOT NULL,
	`DATE` DATE,
	`STATUS` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`RESEARCHSUBJECTTABLE_ID`)
);

CREATE TABLE `SpecimenTable` (
	`SPECIMENTABLE_ID` VARCHAR(191) NOT NULL,
	`COLLECTED` DATE,
	`STATUS` VARCHAR(2048),
	`ACCESSION` VARCHAR(2048),
	`CONTAINER` VARCHAR(2048),
	`BODYSITE` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`TYPE` VARCHAR(2048),
	`CONTAINER_ID` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`SPECIMENTABLE_ID`)
);

CREATE TABLE `VerificationResultTable` (
	`VERIFICATIONRESULTTABLE_ID` VARCHAR(191) NOT NULL,
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`VERIFICATIONRESULTTABLE_ID`)
);

CREATE TABLE `SlotTable` (
	`SLOTTABLE_ID` VARCHAR(191) NOT NULL,
	`SERVICE_CATEGORY` VARCHAR(2048),
	`STATUS` VARCHAR(2048),
	`APPOINTMENT_TYPE` VARCHAR(2048),
	`SPECIALTY` VARCHAR(2048),
	`START` DATE,
	`IDENTIFIER` VARCHAR(2048),
	`SERVICE_TYPE` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`SLOTTABLE_ID`)
);

CREATE TABLE `MedicinalProductPharmaceuticalTable` (
	`MEDICINALPRODUCTPHARMACEUTICALTABLE_ID` VARCHAR(191) NOT NULL,
	`ROUTE` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`TARGET_SPECIES` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`MEDICINALPRODUCTPHARMACEUTICALTABLE_ID`)
);

CREATE TABLE `MedicinalProductIndicationTable` (
	`MEDICINALPRODUCTINDICATIONTABLE_ID` VARCHAR(191) NOT NULL,
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`MEDICINALPRODUCTINDICATIONTABLE_ID`)
);

CREATE TABLE `AllergyIntoleranceTable` (
	`ALLERGYINTOLERANCETABLE_ID` VARCHAR(191) NOT NULL,
	`ROUTE` VARCHAR(2048),
	`LAST_DATE` DATE,
	`MANIFESTATION` VARCHAR(2048),
	`CLINICAL_STATUS` VARCHAR(2048),
	`VERIFICATION_STATUS` VARCHAR(2048),
	`DATE` DATE,
	`CODE` VARCHAR(2048),
	`CRITICALITY` VARCHAR(2048),
	`CATEGORY` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`TYPE` VARCHAR(2048),
	`SEVERITY` VARCHAR(2048),
	`ONSET` DATE,
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`ALLERGYINTOLERANCETABLE_ID`)
);

CREATE TABLE `SubstanceSpecificationTable` (
	`SUBSTANCESPECIFICATIONTABLE_ID` VARCHAR(191) NOT NULL,
	`CODE` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`SUBSTANCESPECIFICATIONTABLE_ID`)
);

CREATE TABLE `DetectedIssueTable` (
	`DETECTEDISSUETABLE_ID` VARCHAR(191) NOT NULL,
	`CODE` VARCHAR(2048),
	`IDENTIFIED` DATE,
	`IDENTIFIER` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`DETECTEDISSUETABLE_ID`)
);

CREATE TABLE `ConsentTable` (
	`CONSENTTABLE_ID` VARCHAR(191) NOT NULL,
	`DATE` DATE,
	`SECURITY_LABEL` VARCHAR(2048),
	`STATUS` VARCHAR(2048),
	`ACTION` VARCHAR(2048),
	`SCOPE` VARCHAR(2048),
	`CATEGORY` VARCHAR(2048),
	`PERIOD` DATE,
	`PURPOSE` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`CONSENTTABLE_ID`)
);

CREATE TABLE `MedicationAdministrationTable` (
	`MEDICATIONADMINISTRATIONTABLE_ID` VARCHAR(191) NOT NULL,
	`CODE` VARCHAR(2048),
	`STATUS` VARCHAR(2048),
	`REASON_NOT_GIVEN` VARCHAR(2048),
	`EFFECTIVE_TIME` DATE,
	`REASON_GIVEN` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`MEDICATIONADMINISTRATIONTABLE_ID`)
);

CREATE TABLE `CareTeamTable` (
	`CARETEAMTABLE_ID` VARCHAR(191) NOT NULL,
	`DATE` DATE,
	`STATUS` VARCHAR(2048),
	`CATEGORY` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`CARETEAMTABLE_ID`)
);

CREATE TABLE `EpisodeOfCareTable` (
	`EPISODEOFCARETABLE_ID` VARCHAR(191) NOT NULL,
	`DATE` DATE,
	`STATUS` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`TYPE` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`EPISODEOFCARETABLE_ID`)
);

CREATE TABLE `VisionPrescriptionTable` (
	`VISIONPRESCRIPTIONTABLE_ID` VARCHAR(191) NOT NULL,
	`STATUS` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`DATEWRITTEN` DATE,
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`VISIONPRESCRIPTIONTABLE_ID`)
);

CREATE TABLE `CarePlanTable` (
	`CAREPLANTABLE_ID` VARCHAR(191) NOT NULL,
	`DATE` DATE,
	`STATUS` VARCHAR(2048),
	`INSTANTIATES_URI` VARCHAR(512),
	`CATEGORY` VARCHAR(2048),
	`INTENT` VARCHAR(2048),
	`ACTIVITY_DATE` DATE,
	`ACTIVITY_CODE` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`CAREPLANTABLE_ID`)
);

CREATE TABLE `PlanDefinitionTable` (
	`PLANDEFINITIONTABLE_ID` VARCHAR(191) NOT NULL,
	`PUBLISHER` VARCHAR(512),
	`JURISDICTION` VARCHAR(2048),
	`EFFECTIVE` DATE,
	`TOPIC` VARCHAR(2048),
	`CONTEXT` VARCHAR(2048),
	`URL` VARCHAR(512),
	`NAME` VARCHAR(512),
	`DATE` DATE,
	`STATUS` VARCHAR(2048),
	`DESCRIPTION` VARCHAR(512),
	`VERSION` VARCHAR(2048),
	`TITLE` VARCHAR(512),
	`IDENTIFIER` VARCHAR(2048),
	`CONTEXT_QUANTITY` VARCHAR(2048),
	`TYPE` VARCHAR(2048),
	`CONTEXT_TYPE` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`PLANDEFINITIONTABLE_ID`)
);

CREATE TABLE `MedicationKnowledgeTable` (
	`MEDICATIONKNOWLEDGETABLE_ID` VARCHAR(191) NOT NULL,
	`CODE` VARCHAR(2048),
	`SOURCE_COST` VARCHAR(2048),
	`STATUS` VARCHAR(2048),
	`MONITORING_PROGRAM_NAME` VARCHAR(2048),
	`CLASSIFICATION_TYPE` VARCHAR(2048),
	`CLASSIFICATION` VARCHAR(2048),
	`DOSEFORM` VARCHAR(2048),
	`MONOGRAPH_TYPE` VARCHAR(2048),
	`MONITORING_PROGRAM_TYPE` VARCHAR(2048),
	`INGREDIENT_CODE` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`MEDICATIONKNOWLEDGETABLE_ID`)
);

CREATE TABLE `ChargeItemTable` (
	`CHARGEITEMTABLE_ID` VARCHAR(191) NOT NULL,
	`CODE` VARCHAR(2048),
	`FACTOR_OVERRIDE` INT,
	`QUANTITY` VARCHAR(2048),
	`OCCURRENCE` DATE,
	`PRICE_OVERRIDE` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`ENTERED_DATE` DATE,
	`PERFORMER_FUNCTION` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`CHARGEITEMTABLE_ID`)
);

CREATE TABLE `SEARCH_PARAM_RES_EXPRESSIONS` (
	`ID` INT AUTO_INCREMENT,
	`SEARCH_PARAM_NAME` VARCHAR(191) NOT NULL,
	`SEARCH_PARAM_TYPE` VARCHAR(191) NOT NULL,
	`RESOURCE_NAME` VARCHAR(191) NOT NULL,
	`EXPRESSION` VARCHAR(191) NOT NULL,
	PRIMARY KEY(`ID`)
);

CREATE TABLE `OrganizationAffiliationTable` (
	`ORGANIZATIONAFFILIATIONTABLE_ID` VARCHAR(191) NOT NULL,
	`ROLE` VARCHAR(2048),
	`DATE` DATE,
	`ACTIVE` VARCHAR(2048),
	`PHONE` VARCHAR(2048),
	`SPECIALTY` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`EMAIL` VARCHAR(2048),
	`TELECOM` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`ORGANIZATIONAFFILIATIONTABLE_ID`)
);

CREATE TABLE `ListTable` (
	`LISTTABLE_ID` VARCHAR(191) NOT NULL,
	`DATE` DATE,
	`NOTES` VARCHAR(512),
	`EMPTY_REASON` VARCHAR(2048),
	`CODE` VARCHAR(2048),
	`STATUS` VARCHAR(2048),
	`TITLE` VARCHAR(512),
	`IDENTIFIER` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`LISTTABLE_ID`)
);

CREATE TABLE `RiskAssessmentTable` (
	`RISKASSESSMENTTABLE_ID` VARCHAR(191) NOT NULL,
	`DATE` DATE,
	`PROBABILITY` INT,
	`METHOD` VARCHAR(2048),
	`RISK` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`RISKASSESSMENTTABLE_ID`)
);

CREATE TABLE `EncounterTable` (
	`ENCOUNTERTABLE_ID` VARCHAR(191) NOT NULL,
	`PARTICIPANT_TYPE` VARCHAR(2048),
	`DATE` DATE,
	`STATUS` VARCHAR(2048),
	`LENGTH` VARCHAR(2048),
	`REASON_CODE` VARCHAR(2048),
	`SPECIAL_ARRANGEMENT` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`CLASS` VARCHAR(2048),
	`TYPE` VARCHAR(2048),
	`LOCATION_PERIOD` DATE,
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`ENCOUNTERTABLE_ID`)
);

CREATE TABLE `BundleTable` (
	`BUNDLETABLE_ID` VARCHAR(191) NOT NULL,
	`TIMESTAMP` DATE,
	`IDENTIFIER` VARCHAR(2048),
	`TYPE` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`BUNDLETABLE_ID`)
);

CREATE TABLE `ResearchStudyTable` (
	`RESEARCHSTUDYTABLE_ID` VARCHAR(191) NOT NULL,
	`LOCATION` VARCHAR(2048),
	`DATE` DATE,
	`STATUS` VARCHAR(2048),
	`CATEGORY` VARCHAR(2048),
	`FOCUS` VARCHAR(2048),
	`KEYWORD` VARCHAR(2048),
	`TITLE` VARCHAR(512),
	`IDENTIFIER` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`RESEARCHSTUDYTABLE_ID`)
);

CREATE TABLE `CoverageEligibilityResponseTable` (
	`COVERAGEELIGIBILITYRESPONSETABLE_ID` VARCHAR(191) NOT NULL,
	`CREATED` DATE,
	`STATUS` VARCHAR(2048),
	`OUTCOME` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`DISPOSITION` VARCHAR(512),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`COVERAGEELIGIBILITYRESPONSETABLE_ID`)
);

CREATE TABLE `OrganizationTable` (
	`ORGANIZATIONTABLE_ID` VARCHAR(191) NOT NULL,
	`ADDRESS_COUNTRY` VARCHAR(512),
	`ADDRESS_POSTALCODE` VARCHAR(512),
	`ADDRESS_USE` VARCHAR(2048),
	`ACTIVE` VARCHAR(2048),
	`ADDRESS` VARCHAR(512),
	`PHONETIC` VARCHAR(512),
	`IDENTIFIER` VARCHAR(2048),
	`ADDRESS_CITY` VARCHAR(512),
	`TYPE` VARCHAR(2048),
	`ADDRESS_STATE` VARCHAR(512),
	`NAME` VARCHAR(512),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`ORGANIZATIONTABLE_ID`)
);

CREATE TABLE `CommunicationTable` (
	`COMMUNICATIONTABLE_ID` VARCHAR(191) NOT NULL,
	`RECEIVED` DATE,
	`STATUS` VARCHAR(2048),
	`MEDIUM` VARCHAR(2048),
	`INSTANTIATES_URI` VARCHAR(512),
	`CATEGORY` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`SENT` DATE,
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`COMMUNICATIONTABLE_ID`)
);

CREATE TABLE `ClinicalImpressionTable` (
	`CLINICALIMPRESSIONTABLE_ID` VARCHAR(191) NOT NULL,
	`DATE` DATE,
	`STATUS` VARCHAR(2048),
	`FINDING_CODE` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`CLINICALIMPRESSIONTABLE_ID`)
);

CREATE TABLE `StructureDefinitionTable` (
	`STRUCTUREDEFINITIONTABLE_ID` VARCHAR(191) NOT NULL,
	`PATH` VARCHAR(2048),
	`DERIVATION` VARCHAR(2048),
	`PUBLISHER` VARCHAR(512),
	`JURISDICTION` VARCHAR(2048),
	`BASE_PATH` VARCHAR(2048),
	`EXPERIMENTAL` VARCHAR(2048),
	`KEYWORD` VARCHAR(2048),
	`CONTEXT` VARCHAR(2048),
	`ABSTRACT` VARCHAR(2048),
	`URL` VARCHAR(512),
	`NAME` VARCHAR(512),
	`DATE` DATE,
	`STATUS` VARCHAR(2048),
	`DESCRIPTION` VARCHAR(512),
	`KIND` VARCHAR(2048),
	`VERSION` VARCHAR(2048),
	`EXT_CONTEXT` VARCHAR(2048),
	`TITLE` VARCHAR(512),
	`CONTEXT_QUANTITY` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`TYPE` VARCHAR(512),
	`CONTEXT_TYPE` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`STRUCTUREDEFINITIONTABLE_ID`)
);

CREATE TABLE `NamingSystemTable` (
	`NAMINGSYSTEMTABLE_ID` VARCHAR(191) NOT NULL,
	`PUBLISHER` VARCHAR(512),
	`RESPONSIBLE` VARCHAR(512),
	`CONTACT` VARCHAR(512),
	`JURISDICTION` VARCHAR(2048),
	`VALUE` VARCHAR(512),
	`ID_TYPE` VARCHAR(2048),
	`CONTEXT` VARCHAR(2048),
	`TELECOM` VARCHAR(2048),
	`NAME` VARCHAR(512),
	`DATE` DATE,
	`STATUS` VARCHAR(2048),
	`DESCRIPTION` VARCHAR(512),
	`PERIOD` DATE,
	`KIND` VARCHAR(2048),
	`CONTEXT_QUANTITY` VARCHAR(2048),
	`TYPE` VARCHAR(2048),
	`CONTEXT_TYPE` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`NAMINGSYSTEMTABLE_ID`)
);

CREATE TABLE `AppointmentTable` (
	`APPOINTMENTTABLE_ID` VARCHAR(191) NOT NULL,
	`DATE` DATE,
	`SERVICE_CATEGORY` VARCHAR(2048),
	`PART_STATUS` VARCHAR(2048),
	`STATUS` VARCHAR(2048),
	`APPOINTMENT_TYPE` VARCHAR(2048),
	`REASON_CODE` VARCHAR(2048),
	`SPECIALTY` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`SERVICE_TYPE` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`APPOINTMENTTABLE_ID`)
);

CREATE TABLE `DeviceRequestTable` (
	`DEVICEREQUESTTABLE_ID` VARCHAR(191) NOT NULL,
	`CODE` VARCHAR(2048),
	`EVENT_DATE` DATE,
	`STATUS` VARCHAR(2048),
	`INSTANTIATES_URI` VARCHAR(512),
	`AUTHORED_ON` DATE,
	`INTENT` VARCHAR(2048),
	`GROUP_IDENTIFIER` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`DEVICEREQUESTTABLE_ID`)
);

CREATE TABLE `EnrollmentResponseTable` (
	`ENROLLMENTRESPONSETABLE_ID` VARCHAR(191) NOT NULL,
	`STATUS` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`ENROLLMENTRESPONSETABLE_ID`)
);

CREATE TABLE `SubscriptionTable` (
	`SUBSCRIPTIONTABLE_ID` VARCHAR(191) NOT NULL,
	`CRITERIA` VARCHAR(512),
	`CONTACT` VARCHAR(2048),
	`STATUS` VARCHAR(2048),
	`PAYLOAD` VARCHAR(2048),
	`TYPE` VARCHAR(2048),
	`URL` VARCHAR(512),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`SUBSCRIPTIONTABLE_ID`)
);

CREATE TABLE `BasicTable` (
	`BASICTABLE_ID` VARCHAR(191) NOT NULL,
	`CODE` VARCHAR(2048),
	`CREATED` DATE,
	`IDENTIFIER` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`BASICTABLE_ID`)
);

CREATE TABLE `ServiceRequestTable` (
	`SERVICEREQUESTTABLE_ID` VARCHAR(191) NOT NULL,
	`REQUISITION` VARCHAR(2048),
	`CODE` VARCHAR(2048),
	`STATUS` VARCHAR(2048),
	`OCCURRENCE` DATE,
	`INSTANTIATES_URI` VARCHAR(512),
	`PERFORMER_TYPE` VARCHAR(2048),
	`CATEGORY` VARCHAR(2048),
	`INTENT` VARCHAR(2048),
	`AUTHORED` DATE,
	`PRIORITY` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`BODY_SITE` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`SERVICEREQUESTTABLE_ID`)
);

CREATE TABLE `SupplyDeliveryTable` (
	`SUPPLYDELIVERYTABLE_ID` VARCHAR(191) NOT NULL,
	`STATUS` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`SUPPLYDELIVERYTABLE_ID`)
);

CREATE TABLE `MeasureReportTable` (
	`MEASUREREPORTTABLE_ID` VARCHAR(191) NOT NULL,
	`DATE` DATE,
	`STATUS` VARCHAR(2048),
	`PERIOD` DATE,
	`IDENTIFIER` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`MEASUREREPORTTABLE_ID`)
);

CREATE TABLE `OperationDefinitionTable` (
	`OPERATIONDEFINITIONTABLE_ID` VARCHAR(191) NOT NULL,
	`SYSTEM` VARCHAR(2048),
	`PUBLISHER` VARCHAR(512),
	`JURISDICTION` VARCHAR(2048),
	`INSTANCE` VARCHAR(2048),
	`CONTEXT` VARCHAR(2048),
	`URL` VARCHAR(512),
	`NAME` VARCHAR(512),
	`DATE` DATE,
	`CODE` VARCHAR(2048),
	`STATUS` VARCHAR(2048),
	`DESCRIPTION` VARCHAR(512),
	`KIND` VARCHAR(2048),
	`VERSION` VARCHAR(2048),
	`TITLE` VARCHAR(512),
	`CONTEXT_QUANTITY` VARCHAR(2048),
	`TYPE` VARCHAR(2048),
	`CONTEXT_TYPE` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`OPERATIONDEFINITIONTABLE_ID`)
);

CREATE TABLE `EffectEvidenceSynthesisTable` (
	`EFFECTEVIDENCESYNTHESISTABLE_ID` VARCHAR(191) NOT NULL,
	`PUBLISHER` VARCHAR(512),
	`JURISDICTION` VARCHAR(2048),
	`EFFECTIVE` DATE,
	`CONTEXT` VARCHAR(2048),
	`URL` VARCHAR(512),
	`NAME` VARCHAR(512),
	`DATE` DATE,
	`STATUS` VARCHAR(2048),
	`DESCRIPTION` VARCHAR(512),
	`VERSION` VARCHAR(2048),
	`TITLE` VARCHAR(512),
	`IDENTIFIER` VARCHAR(2048),
	`CONTEXT_QUANTITY` VARCHAR(2048),
	`CONTEXT_TYPE` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`EFFECTEVIDENCESYNTHESISTABLE_ID`)
);

CREATE TABLE `ObservationTable` (
	`OBSERVATIONTABLE_ID` VARCHAR(191) NOT NULL,
	`COMPONENT_CODE` VARCHAR(2048),
	`VALUE_QUANTITY` VARCHAR(2048),
	`COMBO_CODE` VARCHAR(2048),
	`VALUE_DATE` DATE,
	`DATE` DATE,
	`VALUE_STRING` VARCHAR(512),
	`COMBO_DATA_ABSENT_REASON` VARCHAR(2048),
	`CODE` VARCHAR(2048),
	`STATUS` VARCHAR(2048),
	`CATEGORY` VARCHAR(2048),
	`COMBO_VALUE_QUANTITY` VARCHAR(2048),
	`VALUE_CONCEPT` VARCHAR(2048),
	`METHOD` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`COMPONENT_DATA_ABSENT_REASON` VARCHAR(2048),
	`DATA_ABSENT_REASON` VARCHAR(2048),
	`COMPONENT_VALUE_QUANTITY` VARCHAR(2048),
	`COMPONENT_VALUE_CONCEPT` VARCHAR(2048),
	`COMBO_VALUE_CONCEPT` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`OBSERVATIONTABLE_ID`)
);

CREATE TABLE `QuestionnaireResponseTable` (
	`QUESTIONNAIRERESPONSETABLE_ID` VARCHAR(191) NOT NULL,
	`STATUS` VARCHAR(2048),
	`AUTHORED` DATE,
	`IDENTIFIER` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`QUESTIONNAIRERESPONSETABLE_ID`)
);

CREATE TABLE `InvoiceTable` (
	`INVOICETABLE_ID` VARCHAR(191) NOT NULL,
	`DATE` DATE,
	`STATUS` VARCHAR(2048),
	`TOTALNET` VARCHAR(2048),
	`PARTICIPANT_ROLE` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`TYPE` VARCHAR(2048),
	`TOTALGROSS` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`INVOICETABLE_ID`)
);

CREATE TABLE `ExampleScenarioTable` (
	`EXAMPLESCENARIOTABLE_ID` VARCHAR(191) NOT NULL,
	`DATE` DATE,
	`PUBLISHER` VARCHAR(512),
	`STATUS` VARCHAR(2048),
	`JURISDICTION` VARCHAR(2048),
	`VERSION` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`CONTEXT_QUANTITY` VARCHAR(2048),
	`CONTEXT` VARCHAR(2048),
	`URL` VARCHAR(512),
	`CONTEXT_TYPE` VARCHAR(2048),
	`NAME` VARCHAR(512),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`EXAMPLESCENARIOTABLE_ID`)
);

CREATE TABLE `SupplyRequestTable` (
	`SUPPLYREQUESTTABLE_ID` VARCHAR(191) NOT NULL,
	`DATE` DATE,
	`STATUS` VARCHAR(2048),
	`CATEGORY` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`SUPPLYREQUESTTABLE_ID`)
);

CREATE TABLE `AdverseEventTable` (
	`ADVERSEEVENTTABLE_ID` VARCHAR(191) NOT NULL,
	`DATE` DATE,
	`CATEGORY` VARCHAR(2048),
	`SERIOUSNESS` VARCHAR(2048),
	`ACTUALITY` VARCHAR(2048),
	`SEVERITY` VARCHAR(2048),
	`EVENT` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`ADVERSEEVENTTABLE_ID`)
);

CREATE TABLE `FamilyMemberHistoryTable` (
	`FAMILYMEMBERHISTORYTABLE_ID` VARCHAR(191) NOT NULL,
	`DATE` DATE,
	`CODE` VARCHAR(2048),
	`STATUS` VARCHAR(2048),
	`INSTANTIATES_URI` VARCHAR(512),
	`SEX` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`RELATIONSHIP` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`FAMILYMEMBERHISTORYTABLE_ID`)
);

CREATE TABLE `DeviceTable` (
	`DEVICETABLE_ID` VARCHAR(191) NOT NULL,
	`STATUS` VARCHAR(2048),
	`UDI_DI` VARCHAR(512),
	`UDI_CARRIER` VARCHAR(512),
	`DEVICE_NAME` VARCHAR(512),
	`IDENTIFIER` VARCHAR(2048),
	`MODEL` VARCHAR(512),
	`MANUFACTURER` VARCHAR(512),
	`TYPE` VARCHAR(2048),
	`URL` VARCHAR(512),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`DEVICETABLE_ID`)
);

CREATE TABLE `EvidenceTable` (
	`EVIDENCETABLE_ID` VARCHAR(191) NOT NULL,
	`PUBLISHER` VARCHAR(512),
	`JURISDICTION` VARCHAR(2048),
	`EFFECTIVE` DATE,
	`TOPIC` VARCHAR(2048),
	`CONTEXT` VARCHAR(2048),
	`URL` VARCHAR(512),
	`NAME` VARCHAR(512),
	`DATE` DATE,
	`STATUS` VARCHAR(2048),
	`DESCRIPTION` VARCHAR(512),
	`VERSION` VARCHAR(2048),
	`TITLE` VARCHAR(512),
	`IDENTIFIER` VARCHAR(2048),
	`CONTEXT_QUANTITY` VARCHAR(2048),
	`CONTEXT_TYPE` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`EVIDENCETABLE_ID`)
);

CREATE TABLE `ActivityDefinitionTable` (
	`ACTIVITYDEFINITIONTABLE_ID` VARCHAR(191) NOT NULL,
	`PUBLISHER` VARCHAR(512),
	`JURISDICTION` VARCHAR(2048),
	`EFFECTIVE` DATE,
	`TOPIC` VARCHAR(2048),
	`CONTEXT` VARCHAR(2048),
	`URL` VARCHAR(512),
	`NAME` VARCHAR(512),
	`DATE` DATE,
	`STATUS` VARCHAR(2048),
	`DESCRIPTION` VARCHAR(512),
	`VERSION` VARCHAR(2048),
	`TITLE` VARCHAR(512),
	`IDENTIFIER` VARCHAR(2048),
	`CONTEXT_QUANTITY` VARCHAR(2048),
	`CONTEXT_TYPE` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`ACTIVITYDEFINITIONTABLE_ID`)
);

CREATE TABLE `PractitionerTable` (
	`PRACTITIONERTABLE_ID` VARCHAR(191) NOT NULL,
	`ADDRESS_COUNTRY` VARCHAR(512),
	`ADDRESS_POSTALCODE` VARCHAR(512),
	`ACTIVE` VARCHAR(2048),
	`PHONE` VARCHAR(2048),
	`ADDRESS_CITY` VARCHAR(512),
	`EMAIL` VARCHAR(2048),
	`ADDRESS_STATE` VARCHAR(512),
	`TELECOM` VARCHAR(2048),
	`NAME` VARCHAR(512),
	`FAMILY` VARCHAR(512),
	`ADDRESS_USE` VARCHAR(2048),
	`GIVEN` VARCHAR(512),
	`ADDRESS` VARCHAR(512),
	`GENDER` VARCHAR(2048),
	`PHONETIC` VARCHAR(512),
	`IDENTIFIER` VARCHAR(2048),
	`COMMUNICATION` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`PRACTITIONERTABLE_ID`)
);

CREATE TABLE `PersonTable` (
	`PERSONTABLE_ID` VARCHAR(191) NOT NULL,
	`ADDRESS_COUNTRY` VARCHAR(512),
	`ADDRESS_POSTALCODE` VARCHAR(512),
	`PHONE` VARCHAR(2048),
	`BIRTHDATE` DATE,
	`ADDRESS_CITY` VARCHAR(512),
	`EMAIL` VARCHAR(2048),
	`ADDRESS_STATE` VARCHAR(512),
	`TELECOM` VARCHAR(2048),
	`NAME` VARCHAR(512),
	`ADDRESS_USE` VARCHAR(2048),
	`ADDRESS` VARCHAR(512),
	`GENDER` VARCHAR(2048),
	`PHONETIC` VARCHAR(512),
	`IDENTIFIER` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`PERSONTABLE_ID`)
);

CREATE TABLE `GroupTable` (
	`GROUPTABLE_ID` VARCHAR(191) NOT NULL,
	`CHARACTERISTIC` VARCHAR(2048),
	`CODE` VARCHAR(2048),
	`EXCLUDE` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`VALUE` VARCHAR(2048),
	`ACTUAL` VARCHAR(2048),
	`TYPE` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`GROUPTABLE_ID`)
);

CREATE TABLE `PractitionerRoleTable` (
	`PRACTITIONERROLETABLE_ID` VARCHAR(191) NOT NULL,
	`ROLE` VARCHAR(2048),
	`DATE` DATE,
	`ACTIVE` VARCHAR(2048),
	`PHONE` VARCHAR(2048),
	`SPECIALTY` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`EMAIL` VARCHAR(2048),
	`TELECOM` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`PRACTITIONERROLETABLE_ID`)
);

CREATE TABLE `ImagingStudyTable` (
	`IMAGINGSTUDYTABLE_ID` VARCHAR(191) NOT NULL,
	`STATUS` VARCHAR(2048),
	`DICOM_CLASS` VARCHAR(2048),
	`SERIES` VARCHAR(2048),
	`MODALITY` VARCHAR(2048),
	`STARTED` DATE,
	`BODYSITE` VARCHAR(2048),
	`INSTANCE` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`REASON` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`IMAGINGSTUDYTABLE_ID`)
);

CREATE TABLE `MedicinalProductAuthorizationTable` (
	`MEDICINALPRODUCTAUTHORIZATIONTABLE_ID` VARCHAR(191) NOT NULL,
	`STATUS` VARCHAR(2048),
	`COUNTRY` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`MEDICINALPRODUCTAUTHORIZATIONTABLE_ID`)
);

CREATE TABLE `ClaimResponseTable` (
	`CLAIMRESPONSETABLE_ID` VARCHAR(191) NOT NULL,
	`CREATED` DATE,
	`STATUS` VARCHAR(2048),
	`OUTCOME` VARCHAR(2048),
	`USE` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`PAYMENT_DATE` DATE,
	`DISPOSITION` VARCHAR(512),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`CLAIMRESPONSETABLE_ID`)
);

CREATE TABLE `MedicinalProductContraindicationTable` (
	`MEDICINALPRODUCTCONTRAINDICATIONTABLE_ID` VARCHAR(191) NOT NULL,
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`MEDICINALPRODUCTCONTRAINDICATIONTABLE_ID`)
);

CREATE TABLE `InsurancePlanTable` (
	`INSURANCEPLANTABLE_ID` VARCHAR(191) NOT NULL,
	`ADDRESS_COUNTRY` VARCHAR(512),
	`ADDRESS_POSTALCODE` VARCHAR(512),
	`STATUS` VARCHAR(2048),
	`ADDRESS_USE` VARCHAR(2048),
	`ADDRESS` VARCHAR(512),
	`PHONETIC` VARCHAR(512),
	`IDENTIFIER` VARCHAR(2048),
	`ADDRESS_CITY` VARCHAR(512),
	`TYPE` VARCHAR(2048),
	`ADDRESS_STATE` VARCHAR(512),
	`NAME` VARCHAR(512),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`INSURANCEPLANTABLE_ID`)
);

CREATE TABLE `MedicationStatementTable` (
	`MEDICATIONSTATEMENTTABLE_ID` VARCHAR(191) NOT NULL,
	`CODE` VARCHAR(2048),
	`STATUS` VARCHAR(2048),
	`CATEGORY` VARCHAR(2048),
	`EFFECTIVE` DATE,
	`IDENTIFIER` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`MEDICATIONSTATEMENTTABLE_ID`)
);

CREATE TABLE `FlagTable` (
	`FLAGTABLE_ID` VARCHAR(191) NOT NULL,
	`DATE` DATE,
	`IDENTIFIER` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`FLAGTABLE_ID`)
);

CREATE TABLE `ExplanationOfBenefitTable` (
	`EXPLANATIONOFBENEFITTABLE_ID` VARCHAR(191) NOT NULL,
	`CREATED` DATE,
	`STATUS` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`DISPOSITION` VARCHAR(512),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`EXPLANATIONOFBENEFITTABLE_ID`)
);

CREATE TABLE `LocationTable` (
	`LOCATIONTABLE_ID` VARCHAR(191) NOT NULL,
	`ADDRESS_COUNTRY` VARCHAR(512),
	`ADDRESS_POSTALCODE` VARCHAR(512),
	`STATUS` VARCHAR(2048),
	`ADDRESS_USE` VARCHAR(2048),
	`ADDRESS` VARCHAR(512),
	`OPERATIONAL_STATUS` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`ADDRESS_CITY` VARCHAR(512),
	`TYPE` VARCHAR(2048),
	`ADDRESS_STATE` VARCHAR(512),
	`NAME` VARCHAR(512),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`LOCATIONTABLE_ID`)
);

CREATE TABLE `DeviceMetricTable` (
	`DEVICEMETRICTABLE_ID` VARCHAR(191) NOT NULL,
	`CATEGORY` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`TYPE` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`DEVICEMETRICTABLE_ID`)
);

CREATE TABLE `ImmunizationRecommendationTable` (
	`IMMUNIZATIONRECOMMENDATIONTABLE_ID` VARCHAR(191) NOT NULL,
	`DATE` DATE,
	`STATUS` VARCHAR(2048),
	`TARGET_DISEASE` VARCHAR(2048),
	`VACCINE_TYPE` VARCHAR(2048),
	`IDENTIFIER` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`IMMUNIZATIONRECOMMENDATIONTABLE_ID`)
);

CREATE TABLE `DocumentManifestTable` (
	`DOCUMENTMANIFESTTABLE_ID` VARCHAR(191) NOT NULL,
	`CREATED` DATE,
	`STATUS` VARCHAR(2048),
	`RELATED_ID` VARCHAR(2048),
	`DESCRIPTION` VARCHAR(512),
	`SOURCE` VARCHAR(512),
	`IDENTIFIER` VARCHAR(2048),
	`TYPE` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`DOCUMENTMANIFESTTABLE_ID`)
);

CREATE TABLE `ValueSetTable` (
	`VALUESETTABLE_ID` VARCHAR(191) NOT NULL,
	`PUBLISHER` VARCHAR(512),
	`JURISDICTION` VARCHAR(2048),
	`CONTEXT` VARCHAR(2048),
	`URL` VARCHAR(512),
	`NAME` VARCHAR(512),
	`DATE` DATE,
	`CODE` VARCHAR(2048),
	`STATUS` VARCHAR(2048),
	`DESCRIPTION` VARCHAR(512),
	`EXPANSION` VARCHAR(512),
	`VERSION` VARCHAR(2048),
	`REFERENCE` VARCHAR(512),
	`TITLE` VARCHAR(512),
	`IDENTIFIER` VARCHAR(2048),
	`CONTEXT_QUANTITY` VARCHAR(2048),
	`CONTEXT_TYPE` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`VALUESETTABLE_ID`)
);

CREATE TABLE `EvidenceVariableTable` (
	`EVIDENCEVARIABLETABLE_ID` VARCHAR(191) NOT NULL,
	`PUBLISHER` VARCHAR(512),
	`JURISDICTION` VARCHAR(2048),
	`EFFECTIVE` DATE,
	`TOPIC` VARCHAR(2048),
	`CONTEXT` VARCHAR(2048),
	`URL` VARCHAR(512),
	`NAME` VARCHAR(512),
	`DATE` DATE,
	`STATUS` VARCHAR(2048),
	`DESCRIPTION` VARCHAR(512),
	`VERSION` VARCHAR(2048),
	`TITLE` VARCHAR(512),
	`IDENTIFIER` VARCHAR(2048),
	`CONTEXT_QUANTITY` VARCHAR(2048),
	`CONTEXT_TYPE` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`EVIDENCEVARIABLETABLE_ID`)
);

CREATE TABLE `RelatedPersonTable` (
	`RELATEDPERSONTABLE_ID` VARCHAR(191) NOT NULL,
	`ADDRESS_COUNTRY` VARCHAR(512),
	`ADDRESS_POSTALCODE` VARCHAR(512),
	`ACTIVE` VARCHAR(2048),
	`PHONE` VARCHAR(2048),
	`BIRTHDATE` DATE,
	`ADDRESS_CITY` VARCHAR(512),
	`EMAIL` VARCHAR(2048),
	`ADDRESS_STATE` VARCHAR(512),
	`TELECOM` VARCHAR(2048),
	`NAME` VARCHAR(512),
	`ADDRESS_USE` VARCHAR(2048),
	`ADDRESS` VARCHAR(512),
	`GENDER` VARCHAR(2048),
	`PHONETIC` VARCHAR(512),
	`IDENTIFIER` VARCHAR(2048),
	`RELATIONSHIP` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`RELATEDPERSONTABLE_ID`)
);

CREATE TABLE `TestReportTable` (
	`TESTREPORTTABLE_ID` VARCHAR(191) NOT NULL,
	`ISSUED` DATE,
	`PARTICIPANT` VARCHAR(512),
	`TESTER` VARCHAR(512),
	`IDENTIFIER` VARCHAR(2048),
	`RESULT` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`TESTREPORTTABLE_ID`)
);

CREATE TABLE `TestScriptTable` (
	`TESTSCRIPTTABLE_ID` VARCHAR(191) NOT NULL,
	`PUBLISHER` VARCHAR(512),
	`JURISDICTION` VARCHAR(2048),
	`CONTEXT` VARCHAR(2048),
	`URL` VARCHAR(512),
	`NAME` VARCHAR(512),
	`DATE` DATE,
	`STATUS` VARCHAR(2048),
	`DESCRIPTION` VARCHAR(512),
	`VERSION` VARCHAR(2048),
	`TESTSCRIPT_CAPABILITY` VARCHAR(512),
	`TITLE` VARCHAR(512),
	`IDENTIFIER` VARCHAR(2048),
	`CONTEXT_QUANTITY` VARCHAR(2048),
	`CONTEXT_TYPE` VARCHAR(2048),
	`VERSION_ID` INT NOT NULL,
	`CREATED_AT` DATETIME NOT NULL,
	`UPDATED_AT` DATETIME NOT NULL,
	`LAST_UPDATED` DATETIME NOT NULL,
	`RESOURCE_JSON` LONGBLOB NOT NULL,
	PRIMARY KEY(`TESTSCRIPTTABLE_ID`)
);


