#!/usr/bin/env bash

set -euo pipefail

# ── Resolve script directory and CSV path ─────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CSV_FILE="${SCRIPT_DIR}/../assets/r4-searchParam-Expression.csv"

# ── Defaults ──────────────────────────────────────────────────────────────────
TABLE_NAME="SEARCH_PARAM_RES_EXPRESSIONS"
OUT_DIR="$SCRIPT_DIR"
SCHEMA=""
PREPEND_DROP="false"
PREPEND_CREATE="false"

# ── Colors ────────────────────────────────────────────────────────────────────
if [ -t 1 ]; then
  RED='\033[0;31m'; GREEN='\033[0;32m'; CYAN='\033[0;36m'
  YELLOW='\033[1;33m'; BOLD='\033[1m'; RESET='\033[0m'
else
  RED=''; GREEN=''; CYAN=''; YELLOW=''; BOLD=''; RESET=''
fi

log_info()  { echo -e "${CYAN}[INFO]${RESET}  $*"; }
log_ok()    { echo -e "${GREEN}[OK]${RESET}    $*"; }
log_warn()  { echo -e "${YELLOW}[WARN]${RESET}  $*"; }
log_error() { echo -e "${RED}[ERROR]${RESET} $*" >&2; }
die()       { log_error "$*"; exit 1; }

usage() {
  grep '^#' "$0" | grep -v '^#!/' | sed 's/^# \{0,1\}//'
  exit 0
}

# ── Argument parsing ──────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case "$1" in
    -t|--table)  TABLE_NAME="$2";       shift 2 ;;
    -o|--outdir) OUT_DIR="$2";          shift 2 ;;
    -s|--schema) SCHEMA="$2";           shift 2 ;;
    --drop)      PREPEND_DROP="true";   shift   ;;
    --create)    PREPEND_CREATE="true"; shift   ;;
    -d|--db)     log_warn "-d/--db is ignored: all 3 DB scripts are always generated."; shift 2 ;;
    -h|--help)   usage ;;
    *) die "Unknown option: $1" ;;
  esac
done

# ── Validate ──────────────────────────────────────────────────────────────────
[ -f "$CSV_FILE" ] || die "CSV file not found: $CSV_FILE"
command -v python3 &>/dev/null || die "python3 is required but not found"
mkdir -p "$OUT_DIR"

# ── Python helper ─────────────────────────────────────────────────────────────
PY_HELPER=$(mktemp /tmp/_gi_helper_XXXXXX.py)
trap 'rm -f "$PY_HELPER"' EXIT

cat > "$PY_HELPER" << 'PYEOF'
import csv, os

def env(k, d=""): return os.environ.get(k, d)

csv_file       = env("GI_CSV_FILE")
db_type        = env("GI_DB_TYPE")
table_name     = env("GI_TABLE_NAME", "SEARCH_PARAM_RES_EXPRESSIONS")
output_file    = env("GI_OUTPUT_FILE")
schema         = env("GI_SCHEMA")
prepend_drop   = env("GI_DROP")   == "true"
prepend_create = env("GI_CREATE") == "true"

# Identifier quoting: MySQL uses backticks; PostgreSQL and H2 use double-quotes
def qi(name):
    return f"`{name}`" if db_type == "mysql" else f'"{name}"'

TABLE    = f"{qi(schema)}.{qi(table_name)}" if schema else qi(table_name)
DB_COLS  = ["SEARCH_PARAM_NAME", "SEARCH_PARAM_TYPE", "RESOURCE_NAME", "EXPRESSION", "IS_CUSTOM"]
col_list = ", ".join(qi(c) for c in DB_COLS)

# '' is ANSI SQL standard — works in PostgreSQL, MySQL and H2
def escape(val):
    return "'" + val.replace("'", "''") + "'"

def sql_str(raw):
    return escape(raw.strip())

def sql_bool(val):
    return "TRUE" if val else "FALSE"

# Read CSV — skip header row
with open(csv_file, newline="", encoding="utf-8-sig") as fh:
    reader   = csv.reader(fh)
    next(reader)
    all_rows = list(reader)

total = len(all_rows)

def drop_stmt():
    return f"DROP TABLE IF EXISTS {TABLE};"

def create_stmt():
    if db_type == "mysql":
        return (
            f"CREATE TABLE IF NOT EXISTS {TABLE} (\n"
            f"  {qi('ID')} INT NOT NULL AUTO_INCREMENT,\n"
            f"  {qi('SEARCH_PARAM_NAME')} VARCHAR(191) NOT NULL,\n"
            f"  {qi('SEARCH_PARAM_TYPE')} VARCHAR(191) NOT NULL,\n"
            f"  {qi('RESOURCE_NAME')} VARCHAR(191) NOT NULL,\n"
            f"  {qi('EXPRESSION')} TEXT NOT NULL,\n"
            f"  {qi('IS_CUSTOM')} BOOLEAN DEFAULT FALSE,\n"
            f"  PRIMARY KEY ({qi('ID')})\n"
            f") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;"
        )
    if db_type == "h2":
        return (
            f"CREATE TABLE IF NOT EXISTS {TABLE} (\n"
            f"  {qi('ID')} BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n"
            f"  {qi('SEARCH_PARAM_NAME')} VARCHAR(191) NOT NULL,\n"
            f"  {qi('SEARCH_PARAM_TYPE')} VARCHAR(191) NOT NULL,\n"
            f"  {qi('RESOURCE_NAME')} VARCHAR(191) NOT NULL,\n"
            f"  {qi('EXPRESSION')} TEXT NOT NULL,\n"
            f"  {qi('IS_CUSTOM')} BOOLEAN DEFAULT FALSE\n"
            f");"
        )
    # postgres
    return (
        f"CREATE TABLE IF NOT EXISTS {TABLE} (\n"
        f"  {qi('ID')} SERIAL,\n"
        f"  {qi('SEARCH_PARAM_NAME')} VARCHAR(191) NOT NULL,\n"
        f"  {qi('SEARCH_PARAM_TYPE')} VARCHAR(191) NOT NULL,\n"
        f"  {qi('RESOURCE_NAME')} VARCHAR(191) NOT NULL,\n"
        f"  {qi('EXPRESSION')} TEXT NOT NULL,\n"
        f"  {qi('IS_CUSTOM')} BOOLEAN DEFAULT FALSE,\n"
        f"  PRIMARY KEY ({qi('ID')})\n"
        f");"
    )

# Build output
out = [
    f"-- Source  : {os.path.basename(csv_file)}",
    f"-- Target  : {db_type.upper()}  |  Table: {TABLE}",
    f"-- Rows    : {total}",
    "",
]

if db_type == "mysql":
    out += ["SET NAMES utf8mb4;", "SET FOREIGN_KEY_CHECKS = 0;", ""]
elif db_type == "postgres":
    out += ["SET client_encoding = 'UTF8';", ""]

if prepend_drop:
    out += [drop_stmt(), ""]
if prepend_create:
    out += [create_stmt(), ""]

out += ["BEGIN;", ""]

for row in all_rows:
    while len(row) < 4:
        row.append("")
    vals = ", ".join([
        sql_str(row[0]),   # Search_Parm      -> SEARCH_PARAM_NAME
        sql_str(row[2]),   # Search_Pram_Type -> SEARCH_PARAM_TYPE
        sql_str(row[1]),   # Resource         -> RESOURCE_NAME
        sql_str(row[3]),   # Expression       -> EXPRESSION
        sql_bool(False),   # IS_CUSTOM        -> FALSE
    ])
    out.append(f"INSERT INTO {TABLE} ({col_list}) VALUES ({vals});")

out += ["", "COMMIT;", ""]

if db_type == "mysql":
    out += ["SET FOREIGN_KEY_CHECKS = 1;", ""]

with open(output_file, "w", encoding="utf-8") as fh:
    fh.write("\n".join(out))

print(f"SUCCESS|rows={total}")
PYEOF

# ── Generate scripts for all three DB types ───────────────────────────────────
echo -e "${BOLD}Table      : ${TABLE_NAME}${RESET}"
echo -e "${BOLD}Source CSV : ${CSV_FILE}${RESET}"
echo -e "${BOLD}Output dir : ${OUT_DIR}${RESET}"
echo ""

FAILED=0

for DB in postgres mysql h2; do
  OUT_FILE="${OUT_DIR}/insert_${TABLE_NAME}_${DB}.sql"
  log_info "Generating ${DB} → $(basename "$OUT_FILE")"

  RESULT=$(
    GI_CSV_FILE="$CSV_FILE"      \
    GI_TABLE_NAME="$TABLE_NAME"  \
    GI_DB_TYPE="$DB"             \
    GI_OUTPUT_FILE="$OUT_FILE"   \
    GI_SCHEMA="$SCHEMA"          \
    GI_DROP="$PREPEND_DROP"      \
    GI_CREATE="$PREPEND_CREATE"  \
    python3 "$PY_HELPER"
  ) || { log_error "Failed for $DB"; FAILED=1; continue; }

  if [[ "$RESULT" == SUCCESS* ]]; then
    ROWS=$(echo "$RESULT" | grep -o 'rows=[0-9]*' | cut -d= -f2)
    log_ok "  ${OUT_FILE}  (${ROWS} rows)"
  else
    log_error "  Generation failed for $DB: $RESULT"
    FAILED=1
  fi
done

echo ""
if [ "$FAILED" -eq 0 ]; then
  echo -e "${GREEN}${BOLD}All 3 SQL scripts generated successfully.${RESET}"
else
  echo -e "${RED}${BOLD}One or more scripts failed. Check errors above.${RESET}"
  exit 1
fi
